import { PROMPT_TEMPLATE_SCHEMA_VERSION } from '@/assets/prompt-templates'
import type { PromptTemplate, PromptTemplateVariable } from '@/types'

function createRequiredVariable(
  key: string,
  label: string,
  placeholder: string,
  example: string,
): PromptTemplateVariable {
  return { key, label, placeholder, example, required: true }
}

export const DEFAULT_TEMPLATES: PromptTemplate[] = [
  {
    id: 'tpl-1',
    title: '电影感环境人像',
    summary: '让人物与真实环境共同承担叙事的电影感肖像。',
    content: '在{{scene}}中创作{{person}}的电影感环境人像。人物呈现{{action}}，主体与环境之间保留清晰的叙事关系；采用35mm环境人像视角和{{framing}}，自然透视、浅景深，人物五官与肢体结构准确。使用{{lighting}}作为主光，背景保留明暗层次，整体采用低饱和电影调色和细腻胶片颗粒，画面真实克制，不添加多余文字、水印或无关元素。',
    categoryId: 'people-characters',
    medium: 'photography',
    styleIds: ['cinematic', 'realistic'],
    variables: [
      createRequiredVariable('scene', '拍摄场景', '例如：雨后的旧城区街口', '雨后的旧城区街口'),
      createRequiredVariable('person', '人物设定', '例如：短发女性建筑师', '短发女性建筑师'),
      createRequiredVariable('action', '动作与情绪', '例如：停步回望，神情平静', '停步回望，神情平静'),
      createRequiredVariable('framing', '景别', '例如：半身构图', '半身构图'),
      createRequiredVariable('lighting', '光线', '例如：黄昏侧逆光', '黄昏侧逆光'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-2',
    title: '国风水墨山水',
    summary: '以传统笔墨和留白关系组织具有诗意的山水画面。',
    content: '创作一幅描绘{{landscape}}的东方水墨山水，画面主题为{{mood}}。使用淡墨渲染远景、浓墨刻画近景，以{{composition}}组织山石、水面与云雾，保留大面积呼吸感和自然留白。纸面呈现细腻宣纸纤维、干湿笔触与墨色渗化，色彩以墨黑、灰白和少量{{accentColor}}点染，意境含蓄，不加入现代建筑、摄影光效、立体渲染或可读文字。',
    categoryId: 'landscapes-nature',
    medium: 'illustration',
    styleIds: ['oriental', 'natural', 'minimal'],
    variables: [
      createRequiredVariable('landscape', '山水主题', '例如：云雾中的高山湖泊', '云雾中的高山湖泊'),
      createRequiredVariable('mood', '画面意境', '例如：清寂悠远', '清寂悠远'),
      createRequiredVariable('composition', '构图方式', '例如：纵向深远构图', '纵向深远构图'),
      createRequiredVariable('accentColor', '点染色', '例如：低饱和朱砂红', '低饱和朱砂红'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-3',
    title: '极简产品主视觉',
    summary: '适合新品发布和品牌广告的干净产品主视觉。',
    content: '为{{product}}创作一张极简商业产品主视觉，突出{{sellingPoint}}。产品完整、比例准确，置于{{surface}}之上，使用{{backgroundColor}}的纯净渐变背景和克制的几何空间关系；采用略低于产品的三分之四视角，边缘清晰，材质反射符合真实物理。柔和大面积主光配合窄幅轮廓光，保留可控阴影和适量留白，整体高级、简洁、可用于品牌发布，不出现错误文字、重复产品、水印或杂乱道具。',
    categoryId: 'products-brands',
    medium: 'photography',
    styleIds: ['commercial', 'minimal', 'realistic'],
    variables: [
      createRequiredVariable('product', '产品', '例如：磨砂玻璃香水瓶', '磨砂玻璃香水瓶'),
      createRequiredVariable('sellingPoint', '核心卖点', '例如：透明瓶身与金属瓶盖', '透明瓶身与金属瓶盖'),
      createRequiredVariable('surface', '承托表面', '例如：浅灰石材台面', '浅灰石材台面'),
      createRequiredVariable('backgroundColor', '背景色', '例如：暖米白', '暖米白'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-4',
    title: '温暖动画场景',
    summary: '适合日常叙事、温柔冒险和治愈氛围的手绘场景。',
    content: '绘制{{character}}置身于{{scene}}的温暖手绘动画场景，正在{{action}}。采用清晰的前景、中景和远景层次，让人物动作与环境细节共同讲述一个安静的日常故事；画面以{{timeOfDay}}的柔和自然光照明，云朵、植物和建筑具有轻微夸张但保持可信结构。使用水彩与不透明颜料结合的手绘质感，色彩温暖柔和，边缘自然，不使用真实摄影景深、塑料3D材质、品牌标识或可读文字。',
    categoryId: 'narrative-worldbuilding',
    medium: 'illustration',
    styleIds: ['healing', 'natural'],
    variables: [
      createRequiredVariable('character', '角色', '例如：背着画板的少年', '背着画板的少年'),
      createRequiredVariable('scene', '场景', '例如：山坡上的旧车站', '山坡上的旧车站'),
      createRequiredVariable('action', '正在发生的事', '例如：等待最后一班列车', '等待最后一班列车'),
      createRequiredVariable('timeOfDay', '时间与光线', '例如：夏日下午', '夏日下午'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-5',
    title: '赛博朋克城市叙事',
    summary: '构建具有明确人物行动和空间层次的未来城市镜头。',
    content: '创作发生在{{location}}的赛博朋克电影场面，主角{{character}}正在{{event}}。使用24mm广角和略低机位呈现密集城市纵深，前景包含雨水、蒸汽与经过的行人，中景聚焦主角，远景展示高层建筑和交通系统。{{lightingColor}}的霓虹光在湿润路面形成受控反射，暗部仍保留材质细节；画面写实、紧张且有明确视觉焦点，科技元素服务于叙事，不堆叠无意义标牌，不生成乱码、水印或重复人物。',
    categoryId: 'narrative-worldbuilding',
    medium: 'photography',
    styleIds: ['science-fiction', 'cinematic', 'realistic'],
    variables: [
      createRequiredVariable('location', '未来地点', '例如：多层轨道下的商业街', '多层轨道下的商业街'),
      createRequiredVariable('character', '主角', '例如：穿防雨外套的快递员', '穿防雨外套的快递员'),
      createRequiredVariable('event', '剧情动作', '例如：在人群中寻找失联终端', '在人群中寻找失联终端'),
      createRequiredVariable('lightingColor', '霓虹主色', '例如：青蓝与琥珀色', '青蓝与琥珀色'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-6',
    title: '等距微缩空间',
    summary: '将真实空间转化为清晰可读的等距微缩三维模型。',
    content: '将{{space}}设计为等距视角的微缩3D场景，核心活动是{{activity}}。以切开的盒状空间展示完整布局，家具、人物和道具比例统一，动线清楚，局部加入{{signatureDetail}}作为视觉记忆点。使用圆润但不过度玩具化的建模、细腻粘土与哑光材质，柔和环境光配合顶部主光，阴影短而清晰；背景保持纯净，色彩采用{{palette}}，画面精致、有秩序，不出现悬浮物体、错误透视、乱码或水印。',
    categoryId: 'spaces-architecture',
    medium: 'three-dimensional',
    styleIds: ['miniature', 'healing', 'minimal'],
    variables: [
      createRequiredVariable('space', '空间类型', '例如：深夜营业的小书店', '深夜营业的小书店'),
      createRequiredVariable('activity', '核心活动', '例如：店员整理新到书籍', '店员整理新到书籍'),
      createRequiredVariable('signatureDetail', '标志细节', '例如：通向夹层的红色旋梯', '通向夹层的红色旋梯'),
      createRequiredVariable('palette', '配色', '例如：木色、墨绿与暖黄', '木色、墨绿与暖黄'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-7',
    title: '美食氛围特写',
    summary: '突出食物温度、质地和用餐氛围的写实摄影。',
    content: '拍摄{{dish}}的美食摄影特写，突出{{texture}}和刚刚完成烹饪的温度感。餐盘置于{{tableSetting}}中，加入少量与菜品相关的原料和餐具作为陪衬，但不遮挡主体；采用约50mm视角、略高机位和自然景深，焦点落在最具食欲的细节。使用{{lighting}}勾勒蒸汽、油脂或酱汁光泽，色彩真实温暖，餐具边缘与食物结构完整，不出现多余餐盘、漂浮配料、错误文字或水印。',
    categoryId: 'food-still-life',
    medium: 'photography',
    styleIds: ['realistic', 'natural', 'commercial'],
    variables: [
      createRequiredVariable('dish', '食物', '例如：刚出炉的菌菇披萨', '刚出炉的菌菇披萨'),
      createRequiredVariable('texture', '重点质感', '例如：酥脆饼边与融化奶酪', '酥脆饼边与融化奶酪'),
      createRequiredVariable('tableSetting', '桌面环境', '例如：深色木桌与亚麻餐巾', '深色木桌与亚麻餐巾'),
      createRequiredVariable('lighting', '光线', '例如：窗边侧逆光', '窗边侧逆光'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-8',
    title: '扁平信息插画',
    summary: '适合文章头图和传播页面的清晰扁平主题插画。',
    content: '围绕{{topic}}创作一幅扁平信息插画，用{{metaphor}}作为核心视觉隐喻。采用清晰的几何形状、有限层级和{{composition}}，主体轮廓简洁，辅助元素只用于解释主题；使用{{palette}}形成明确对比，并加入轻微纸张噪点避免画面过于机械。整体适合文章头图或数字传播页面，保留可裁切的安全留白，不生成具体品牌标识、乱码、装饰性小字或不必要的写实光影。',
    categoryId: 'graphic-communication',
    medium: 'illustration',
    styleIds: ['minimal', 'editorial'],
    variables: [
      createRequiredVariable('topic', '传播主题', '例如：团队远程协作', '团队远程协作'),
      createRequiredVariable('metaphor', '视觉隐喻', '例如：由不同模块连接成的桥梁', '由不同模块连接成的桥梁'),
      createRequiredVariable('composition', '构图', '例如：中心放射构图', '中心放射构图'),
      createRequiredVariable('palette', '配色', '例如：深蓝、橙色与米白', '深蓝、橙色与米白'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-9',
    title: '时尚杂志棚拍',
    summary: '突出服装廓形、人物姿态和编辑气质的棚拍大片。',
    content: '为{{model}}拍摄一组时尚杂志棚拍主图，重点展示{{outfit}}的廓形与材质。人物采用{{pose}}，神态克制自信，身体结构和服装细节准确；使用中长焦人像视角与{{framing}}，背景为简洁的灰阶影棚空间。大面积柔光作为主光，侧后方窄光勾勒轮廓，整体低饱和、锐利而不过度磨皮，保留真实皮肤纹理和织物细节，不出现多余肢体、错误配饰、文字或水印。',
    categoryId: 'people-characters',
    medium: 'photography',
    styleIds: ['editorial', 'commercial', 'realistic'],
    variables: [
      createRequiredVariable('model', '人物设定', '例如：银色短发的青年模特', '银色短发的青年模特'),
      createRequiredVariable('outfit', '服装造型', '例如：结构感黑色长外套', '结构感黑色长外套'),
      createRequiredVariable('pose', '姿态', '例如：侧身站立并直视镜头', '侧身站立并直视镜头'),
      createRequiredVariable('framing', '景别', '例如：四分之三身', '四分之三身'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-10',
    title: '角色设定展示板',
    summary: '在一张画面中明确呈现原创角色的造型、细节和配色。',
    content: '为原创角色{{character}}制作一张专业角色设定展示板，角色身份是{{role}}。画面包含正面全身主视图、侧面轮廓和两处关键细节放大，服装与装备围绕{{designMotif}}形成统一设计语言；使用{{palette}}，结构线条清楚，材质区分明确，人体比例在各视图中保持一致。采用干净的中性背景和有秩序的编辑排版，不加入大段说明文字、现成IP标识、重复肢体或互相矛盾的服装细节。',
    categoryId: 'people-characters',
    medium: 'illustration',
    styleIds: ['fantasy', 'editorial'],
    variables: [
      createRequiredVariable('character', '角色名称或外形', '例如：鹿角森林信使', '鹿角森林信使'),
      createRequiredVariable('role', '角色身份', '例如：负责传递季节消息的旅行者', '负责传递季节消息的旅行者'),
      createRequiredVariable('designMotif', '设计母题', '例如：树叶、邮袋与铜制铃铛', '树叶、邮袋与铜制铃铛'),
      createRequiredVariable('palette', '角色配色', '例如：苔绿、皮革棕与铜金', '苔绿、皮革棕与铜金'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-11',
    title: '电商白底商品图',
    summary: '结构准确、背景纯净并适合商品详情页的标准主图。',
    content: '拍摄{{product}}的标准电商白底商品图，准确呈现{{keyDetails}}。产品位于画面中心，保持完整轮廓和真实比例，采用{{viewAngle}}，所有可见部件结构正确；背景为无接缝纯白，使用均匀柔和的棚拍光消除脏污色偏，同时保留必要的接触阴影和材质层次。画面清晰、颜色忠实、边缘干净，不添加场景道具、促销文字、装饰边框、重复商品、水印或夸张反射。',
    categoryId: 'products-brands',
    medium: 'photography',
    styleIds: ['commercial', 'minimal', 'realistic'],
    variables: [
      createRequiredVariable('product', '商品', '例如：白色无线耳机充电盒', '白色无线耳机充电盒'),
      createRequiredVariable('keyDetails', '关键细节', '例如：开盖结构、耳机仓与指示灯', '开盖结构、耳机仓与指示灯'),
      createRequiredVariable('viewAngle', '展示角度', '例如：正面略高三分之四视角', '正面略高三分之四视角'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-12',
    title: '高端美妆材质广告',
    summary: '通过精细材质和克制布光塑造高端美妆品牌气质。',
    content: '为{{cosmetic}}创作高端美妆广告画面，视觉主题是{{concept}}。产品与{{materialElement}}形成简洁的前后层次，包装比例、瓶盖连接和标签区域保持准确，但标签不生成具体文字；采用近距离三分之四视角，突出玻璃、金属或液体的真实材质。使用{{lighting}}制造柔和渐变、高光边缘和干净阴影，整体配色克制奢华，保留大面积品牌留白，不出现多余瓶体、溢出液体、乱码或水印。',
    categoryId: 'products-brands',
    medium: 'photography',
    styleIds: ['luxury', 'commercial', 'minimal'],
    variables: [
      createRequiredVariable('cosmetic', '美妆产品', '例如：琥珀色精华液瓶', '琥珀色精华液瓶'),
      createRequiredVariable('concept', '视觉主题', '例如：夜间修护与水分屏障', '夜间修护与水分屏障'),
      createRequiredVariable('materialElement', '搭配材质', '例如：半透明冰晶与深色石材', '半透明冰晶与深色石材'),
      createRequiredVariable('lighting', '布光', '例如：冷色顶部柔光与暖色轮廓光', '冷色顶部柔光与暖色轮廓光'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-13',
    title: '饮品广告飞溅瞬间',
    summary: '用凝固的液体动态突出饮品口感与清爽卖点。',
    content: '为{{drink}}拍摄动态饮品广告，核心卖点是{{sellingPoint}}。容器垂直稳定地位于画面中心，周围出现受控的液体飞溅、{{garnish}}和细小水珠，动态方向围绕产品形成视觉引导，不遮挡主体轮廓；使用高速摄影质感和近距离标准视角，液体透明度与重力关系可信。{{backgroundColor}}背景配合明亮侧逆光，色彩清爽、材质锐利，不生成额外容器、错误商标、乱码、水印或不合理漂浮物。',
    categoryId: 'food-still-life',
    medium: 'photography',
    styleIds: ['commercial', 'realistic'],
    variables: [
      createRequiredVariable('drink', '饮品', '例如：透明玻璃瓶装柚子气泡水', '透明玻璃瓶装柚子气泡水'),
      createRequiredVariable('sellingPoint', '核心卖点', '例如：冰凉清爽与细密气泡', '冰凉清爽与细密气泡'),
      createRequiredVariable('garnish', '搭配元素', '例如：新鲜柚子片与薄荷叶', '新鲜柚子片与薄荷叶'),
      createRequiredVariable('backgroundColor', '背景色', '例如：明亮浅青色', '明亮浅青色'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-14',
    title: '古典静物油画',
    summary: '以古典绘画的光影和材质秩序组织器物与果实。',
    content: '创作一幅以{{objects}}为主体的古典静物油画，整体情绪为{{mood}}。物件置于{{setting}}上，通过高低错落和轻微重叠形成稳定三角构图，每件物品仍保持清晰轮廓和可信材质；单一侧上方光源照亮主要物件，背景逐渐沉入暗部，形成克制的明暗对比。使用层层罩染、细腻笔触和{{palette}}，保留画布纹理，不加入现代包装、摄影虚化、塑料质感、文字或水印。',
    categoryId: 'food-still-life',
    medium: 'illustration',
    styleIds: ['retro', 'natural'],
    variables: [
      createRequiredVariable('objects', '静物组合', '例如：石榴、银杯与白色亚麻布', '石榴、银杯与白色亚麻布'),
      createRequiredVariable('mood', '画面情绪', '例如：安静而丰盛', '安静而丰盛'),
      createRequiredVariable('setting', '承托环境', '例如：深色木桌', '深色木桌'),
      createRequiredVariable('palette', '色彩倾向', '例如：酒红、深褐与柔和金色', '酒红、深褐与柔和金色'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-15',
    title: '室内设计效果图',
    summary: '强调空间布局、材料关系和自然采光的写实室内视觉。',
    content: '为{{roomType}}创作写实室内设计效果图，设计方向为{{designStyle}}。从入口附近以约24mm广角观察空间，垂直线保持端正，完整展示主要功能区、家具尺度和通行关系；重点使用{{materials}}，不同表面具有准确的粗糙度、反射和接缝细节。{{lighting}}均匀进入空间，人工辅助光不过曝，明暗层次自然；画面整洁但保留生活感，不出现结构穿插、悬浮家具、重复物件、畸变边缘、文字或水印。',
    categoryId: 'spaces-architecture',
    medium: 'three-dimensional',
    styleIds: ['realistic', 'minimal', 'natural'],
    variables: [
      createRequiredVariable('roomType', '空间类型', '例如：开放式客餐厅', '开放式客餐厅'),
      createRequiredVariable('designStyle', '设计方向', '例如：温暖现代主义', '温暖现代主义'),
      createRequiredVariable('materials', '主要材料', '例如：浅橡木、洞石与米色织物', '浅橡木、洞石与米色织物'),
      createRequiredVariable('lighting', '采光条件', '例如：午后从落地窗进入的自然光', '午后从落地窗进入的自然光'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-16',
    title: '建筑外观叙事摄影',
    summary: '同时表达建筑形体、环境关系和使用者尺度的外观图。',
    content: '拍摄位于{{environment}}中的{{building}}，突出{{architecturalFeature}}。使用24mm移轴建筑摄影视角，保持垂直线准确，从{{viewpoint}}展示完整体量、入口关系和周边景观；加入少量自然活动的人物作为尺度参照，但不遮挡建筑。选择{{weatherAndLight}}塑造立面层次，玻璃、混凝土、木材等材质反射真实，天空与地面不过度处理，不出现倾斜结构、重复窗格、夸张HDR、文字或水印。',
    categoryId: 'spaces-architecture',
    medium: 'photography',
    styleIds: ['realistic', 'editorial'],
    variables: [
      createRequiredVariable('environment', '周边环境', '例如：滨水公共公园', '滨水公共公园'),
      createRequiredVariable('building', '建筑类型', '例如：当代木结构图书馆', '当代木结构图书馆'),
      createRequiredVariable('architecturalFeature', '建筑特点', '例如：层叠挑檐与通透首层', '层叠挑檐与通透首层'),
      createRequiredVariable('viewpoint', '观察位置', '例如：入口广场的斜侧方', '入口广场的斜侧方'),
      createRequiredVariable('weatherAndLight', '天气与光线', '例如：薄云天气下的傍晚柔光', '薄云天气下的傍晚柔光'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-17',
    title: '电影感自然风景',
    summary: '通过尺度、天气与光线关系塑造具有叙事性的自然景观。',
    content: '拍摄{{landscape}}的电影感自然风景，画面表达{{mood}}。使用宽幅构图和{{viewpoint}}，前景安排具有触感的自然元素，中景建立主要地貌，远景延伸至天气与天空；{{weather}}在空间中形成清晰层次，{{lighting}}作为唯一可信主光。色彩低饱和且保留自然冷暖变化，细节丰富但不过度锐化，地貌尺度真实，不加入建筑、人物、奇幻天体、夸张HDR、文字或水印。',
    categoryId: 'landscapes-nature',
    medium: 'photography',
    styleIds: ['cinematic', 'natural', 'realistic'],
    variables: [
      createRequiredVariable('landscape', '自然景观', '例如：冰川融水形成的高山河谷', '冰川融水形成的高山河谷'),
      createRequiredVariable('mood', '情绪', '例如：辽阔而冷静', '辽阔而冷静'),
      createRequiredVariable('viewpoint', '观察位置', '例如：低位贴近河岸', '低位贴近河岸'),
      createRequiredVariable('weather', '天气', '例如：雨后低云正在散开', '雨后低云正在散开'),
      createRequiredVariable('lighting', '光线', '例如：云隙透出的傍晚侧光', '云隙透出的傍晚侧光'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-18',
    title: '自然生态微距',
    summary: '观察微小生物与栖息环境之间真实细腻的生态关系。',
    content: '以微距摄影记录{{subject}}在{{habitat}}中的自然状态，正在{{behavior}}。镜头与主体保持平视或略低角度，焦点落在关键生理结构，浅景深只柔化远处背景，不牺牲主体轮廓；露水、叶片、土壤等环境材质符合真实尺度。使用{{lighting}}呈现细微纹理和半透明结构，色彩自然、克制，不摆拍成人工对称，不出现错误肢体、重复生物、巨大化道具、文字或水印。',
    categoryId: 'landscapes-nature',
    medium: 'photography',
    styleIds: ['natural', 'realistic'],
    variables: [
      createRequiredVariable('subject', '生态主体', '例如：停在苔藓上的蓝色蜻蜓', '停在苔藓上的蓝色蜻蜓'),
      createRequiredVariable('habitat', '栖息环境', '例如：清晨潮湿的溪边植物间', '清晨潮湿的溪边植物间'),
      createRequiredVariable('behavior', '自然行为', '例如：整理带有露水的翅膀', '整理带有露水的翅膀'),
      createRequiredVariable('lighting', '光线', '例如：树叶间透下的柔和逆光', '树叶间透下的柔和逆光'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-19',
    title: '奇幻遗迹探索',
    summary: '以人物尺度和环境线索建立可信的奇幻冒险世界。',
    content: '描绘{{explorer}}进入{{ruins}}的奇幻叙事场景，正在{{discovery}}。使用宽幅远景和略高观察位置，让角色在宏大空间中保持清晰尺度；遗迹结构遵循一致的建造逻辑，前景散落与文明相关的线索，中远景通过雾气和光线延伸深度。{{magicalElement}}作为唯一超自然视觉核心，光效影响周围材质和人物，不堆叠无关特效；整体色彩神秘克制，不出现现代物件、重复人物、乱码或水印。',
    categoryId: 'narrative-worldbuilding',
    medium: 'illustration',
    styleIds: ['fantasy', 'cinematic'],
    variables: [
      createRequiredVariable('explorer', '探索者', '例如：携带旧地图的年轻学者', '携带旧地图的年轻学者'),
      createRequiredVariable('ruins', '遗迹', '例如：被森林吞没的环形石城', '被森林吞没的环形石城'),
      createRequiredVariable('discovery', '发现事件', '例如：打开通向地下星图室的入口', '打开通向地下星图室的入口'),
      createRequiredVariable('magicalElement', '魔法核心', '例如：悬浮在入口上方的蓝色符文', '悬浮在入口上方的蓝色符文'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-20',
    title: '杂志封面视觉',
    summary: '为人物或主题内容建立可承载刊名和标题的编辑封面。',
    content: '为主题{{theme}}设计一张现代杂志封面，核心视觉为{{heroVisual}}。采用{{composition}}建立强主次关系，主体占据明确视觉中心，并在顶部刊名区、左右标题区和底部信息区保留干净空间；使用{{palette}}与克制的编辑摄影或拼贴质感，细节清晰，整体具有当代文化杂志气质。只生成版式占位关系，不生成具体可读文案、随机字母、现成品牌标志、水印或拥挤装饰。',
    categoryId: 'graphic-communication',
    medium: 'graphic-design',
    styleIds: ['editorial', 'typographic'],
    variables: [
      createRequiredVariable('theme', '封面主题', '例如：城市中的独立音乐文化', '城市中的独立音乐文化'),
      createRequiredVariable('heroVisual', '核心视觉', '例如：舞台灯光下的年轻乐队主唱', '舞台灯光下的年轻乐队主唱'),
      createRequiredVariable('composition', '版式结构', '例如：主体偏右的大面积留白构图', '主体偏右的大面积留白构图'),
      createRequiredVariable('palette', '配色', '例如：黑白基底与荧光绿色点缀', '黑白基底与荧光绿色点缀'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-21',
    title: '活动概念海报',
    summary: '以单一视觉概念和清晰信息层级构建传播海报。',
    content: '为{{event}}设计一张概念活动海报，视觉概念是{{visualConcept}}。采用{{layout}}，让核心图形、主标题占位区、日期占位区和辅助信息区形成清晰层级；使用{{palette}}与高对比图形语言，确保缩略图尺寸下仍能识别主题。画面可以保留少量印刷网点、套色偏移或纸张纹理，但不生成具体可读文案、随机乱码、现成商标、水印或无意义装饰元素。',
    categoryId: 'graphic-communication',
    medium: 'graphic-design',
    styleIds: ['typographic', 'editorial', 'retro'],
    variables: [
      createRequiredVariable('event', '活动主题', '例如：夏季独立电影展', '夏季独立电影展'),
      createRequiredVariable('visualConcept', '视觉概念', '例如：胶片被光束切割成城市剪影', '胶片被光束切割成城市剪影'),
      createRequiredVariable('layout', '版式', '例如：纵向非对称网格', '纵向非对称网格'),
      createRequiredVariable('palette', '配色', '例如：深红、奶油白与黑色', '深红、奶油白与黑色'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-22',
    title: '超现实场景合成',
    summary: '把真实元素组合成具有单一清晰概念的不可能场景。',
    content: '创作一幅超现实场景：{{subject}}与{{impossibleRelationship}}形成视觉核心，环境位于{{environment}}。所有元素保持写实材质、统一透视和一致光源，让不可能关系看起来真实可信；使用{{viewpoint}}建立明确尺度，背景简洁并为主体留出呼吸空间。整体情绪为{{mood}}，色彩和阴影自然连续，只保留一个核心悖论，不堆叠无关奇观，不出现结构破碎、重复主体、随机文字或水印。',
    categoryId: 'experimental-abstract',
    medium: 'photography',
    styleIds: ['surreal', 'realistic', 'minimal'],
    variables: [
      createRequiredVariable('subject', '现实主体', '例如：一艘白色帆船', '一艘白色帆船'),
      createRequiredVariable('impossibleRelationship', '不可能关系', '例如：在巨大的透明水滴内部航行', '在巨大的透明水滴内部航行'),
      createRequiredVariable('environment', '环境', '例如：无边的干燥盐湖', '无边的干燥盐湖'),
      createRequiredVariable('viewpoint', '观察视角', '例如：远距离平视宽幅构图', '远距离平视宽幅构图'),
      createRequiredVariable('mood', '情绪', '例如：安静、陌生而明亮', '安静、陌生而明亮'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-23',
    title: '流体材质实验',
    summary: '以材质变化、光线和运动轨迹构建抽象三维视觉。',
    content: '创作一幅以{{material}}为核心的抽象3D材质实验，运动形态为{{motion}}。主体悬浮在纯净空间中，由连续曲面和少量分离液滴构成，厚度、表面张力和重力关系可信；使用{{lighting}}揭示透明度、粗糙度和边缘高光，背景采用{{backgroundColor}}，并以{{accentColor}}形成有限色彩对比。构图集中、细节精致，不加入人物、产品、文字、标志、杂乱粒子或不一致的材质反射。',
    categoryId: 'experimental-abstract',
    medium: 'three-dimensional',
    styleIds: ['abstract', 'surreal', 'minimal'],
    variables: [
      createRequiredVariable('material', '实验材质', '例如：半透明虹彩玻璃液体', '半透明虹彩玻璃液体'),
      createRequiredVariable('motion', '运动形态', '例如：向上扭转并形成环形波峰', '向上扭转并形成环形波峰'),
      createRequiredVariable('lighting', '布光', '例如：顶部大面积柔光与侧后窄光', '顶部大面积柔光与侧后窄光'),
      createRequiredVariable('backgroundColor', '背景色', '例如：深石墨灰', '深石墨灰'),
      createRequiredVariable('accentColor', '点缀色', '例如：电光蓝与少量洋红', '电光蓝与少量洋红'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
  {
    id: 'tpl-24',
    title: '抽象几何秩序',
    summary: '使用有限图形、比例和色彩节奏建立现代抽象画面。',
    content: '围绕{{concept}}创作一幅现代抽象几何作品，以{{shapes}}作为主要视觉元素。采用{{composition}}控制比例、留白和视觉节奏，形状之间只发生清晰的切割、叠加或对齐关系；使用{{palette}}，表面包含轻微纸张颗粒和有限的印刷套色偏差，保持平面性与手工触感。画面简洁但不空洞，不加入具象人物、风景、三维光影、装饰文字、现成标志或水印。',
    categoryId: 'experimental-abstract',
    medium: 'graphic-design',
    styleIds: ['abstract', 'minimal', 'retro'],
    variables: [
      createRequiredVariable('concept', '抽象概念', '例如：稳定与失衡', '稳定与失衡'),
      createRequiredVariable('shapes', '主要形状', '例如：圆、窄长矩形与断开的弧线', '圆、窄长矩形与断开的弧线'),
      createRequiredVariable('composition', '构图秩序', '例如：左下聚集、右上大面积留白', '左下聚集、右上大面积留白'),
      createRequiredVariable('palette', '配色', '例如：砖红、钴蓝、黑色与暖白', '砖红、钴蓝、黑色与暖白'),
    ],
    origin: 'builtin',
    useCount: 0,
    schemaVersion: PROMPT_TEMPLATE_SCHEMA_VERSION,
  },
]
