import type { PromptModuleAssetDefinition } from './types'

export default {
  category: {
    key: 'capture',
    label: '拍摄系统',
    description: '定义相机由何种平台操控，以及该平台独有的持机或运动方式',
    selectionMode: 'multiple',
    maxSelections: 6,
  },
  modules: [
    {
      id: 'module-capture-fixed',
      label: '固定机位',
      prompt: '采用固定机位拍摄，相机由稳定支撑系统承载，机身位置不受摄影者手部自然晃动影响',
      sortOrder: 10,
    },
    {
      id: 'module-capture-handheld',
      label: '人手持拍摄',
      prompt: '采用摄影者人手持机拍摄，相机位置由摄影者身体直接控制，保留现场观察的即时性',
      sortOrder: 20,
    },
    {
      id: 'module-capture-drone',
      label: '无人机拍摄',
      prompt: '采用无人机搭载相机拍摄，使摄影机能够脱离地面支撑并从空中观察主体与环境',
      sortOrder: 30,
    },
    {
      id: 'module-capture-tripod',
      label: '三脚架支撑',
      prompt: '相机安装在稳固三脚架上，支撑点位置明确，保持机身高度与画面轴线稳定',
      sortOrder: 40,
    },
    {
      id: 'module-capture-rigid-mount',
      label: '刚性固定支架',
      prompt: '相机安装在刚性固定支架上，机身与承载结构锁定，不发生手持漂移或意外位移',
      sortOrder: 50,
    },
    {
      id: 'module-capture-fixed-static',
      label: '完全静止',
      prompt: '拍摄过程中保持摄影机位置、朝向与画面旋转角度完全静止，不执行平移、摇摄或跟随',
      sortOrder: 60,
    },
    {
      id: 'module-capture-fixed-pan',
      label: '受控摇摄',
      prompt: '摄影机基座保持固定，仅绕稳定轴线执行受控水平或垂直摇摄，运动轨迹平滑且可重复',
      sortOrder: 70,
    },
    {
      id: 'module-capture-operator-standing',
      label: '站姿持机',
      prompt: '摄影者以自然站姿持机，双脚稳定承重，上肢在身体前方控制相机位置',
      sortOrder: 80,
    },
    {
      id: 'module-capture-operator-crouching',
      label: '蹲姿持机',
      prompt: '摄影者屈膝降低身体重心，以蹲姿手持相机，从低于常规站姿的位置完成拍摄',
      sortOrder: 90,
    },
    {
      id: 'module-capture-operator-ground',
      label: '贴地持机',
      prompt: '摄影者俯身或贴近地面持机，使镜头中心接近承载表面，并由手臂直接微调机位',
      sortOrder: 100,
    },
    {
      id: 'module-capture-height-eye',
      label: '眼平持机',
      prompt: '摄影者将相机保持在自身眼部高度，取景器与视线接近重合，机身由面部附近支撑',
      sortOrder: 110,
    },
    {
      id: 'module-capture-height-chest',
      label: '胸前持机',
      prompt: '摄影者将相机保持在胸部高度，以双手和躯干附近的稳定支点控制取景',
      sortOrder: 120,
    },
    {
      id: 'module-capture-height-waist',
      label: '腰平持机',
      prompt: '摄影者将相机保持在腰部高度，镜头中心明显低于常规眼平取景位置',
      sortOrder: 130,
    },
    {
      id: 'module-capture-height-low',
      label: '低位持机',
      prompt: '摄影者将手持相机降至膝部以下，但仍通过双手直接控制镜头位置和朝向',
      sortOrder: 140,
    },
    {
      id: 'module-capture-height-raised',
      label: '高举持机',
      prompt: '摄影者将相机举过头顶，以伸展手臂获得高于自身眼部的观察位置',
      sortOrder: 150,
    },
    {
      id: 'module-capture-natural-stability',
      label: '自然手持',
      prompt: '保留轻微而连续的自然手持漂移，避免机械锁死感，同时不产生剧烈无序晃动',
      sortOrder: 160,
    },
    {
      id: 'module-capture-gimbal',
      label: '稳定器辅助',
      prompt: '使用手持稳定器隔离步伐和腕部震动，使相机运动平滑，同时保留摄影者主动操控路径',
      sortOrder: 170,
    },
    {
      id: 'module-capture-handheld-observe',
      label: '原地观察',
      prompt: '摄影者在原地手持观察，不随主体移动，仅通过小幅身体调整维持构图',
      sortOrder: 180,
    },
    {
      id: 'module-capture-handheld-follow',
      label: '手持跟拍',
      prompt: '摄影者手持相机随主体同步移动，拍摄距离大致稳定，运动方向连续可读',
      sortOrder: 190,
    },
    {
      id: 'module-capture-drone-low',
      label: '无人机低空',
      prompt: '无人机保持接近地表或建筑低层的低空高度飞行，使环境结构仍具有明显近距离透视',
      sortOrder: 200,
    },
    {
      id: 'module-capture-drone-medium',
      label: '无人机中空',
      prompt: '无人机位于主体上方的中等飞行高度，兼顾主体识别度与周围区域关系',
      sortOrder: 210,
    },
    {
      id: 'module-capture-drone-high',
      label: '无人机高空',
      prompt: '无人机升至高空观察位置，以大范围地貌、建筑群或群体分布作为主要空间信息',
      sortOrder: 220,
    },
    {
      id: 'module-capture-drone-hover',
      label: '悬停拍摄',
      prompt: '无人机在固定空间坐标附近稳定悬停，保持飞行高度和拍摄距离基本不变',
      sortOrder: 230,
    },
    {
      id: 'module-capture-drone-forward',
      label: '向前飞行',
      prompt: '无人机沿明确前进方向持续飞行，摄影机位随飞行路径平稳推进',
      sortOrder: 240,
    },
    {
      id: 'module-capture-drone-orbit',
      label: '环绕飞行',
      prompt: '无人机围绕主要主体执行连续圆弧飞行，保持半径与镜头指向稳定',
      sortOrder: 250,
    },
    {
      id: 'module-capture-drone-follow',
      label: '无人机跟随',
      prompt: '无人机沿主体移动方向进行空中跟随，维持相对距离并连续修正飞行路径',
      sortOrder: 260,
    },
  ],
} satisfies PromptModuleAssetDefinition
