import type { PromptModuleAssetDefinition } from './types'

export default {
  category: {
    key: 'composition',
    label: '构图',
    description: '短名称用于选择，实际组合时注入完整画面组织规则',
    selectionMode: 'single',
    maxSelections: 1,
  },
  modules: [
    {
      id: 'module-composition-thirds',
      label: '三分法',
      prompt: '采用三分法构图，将主体视觉中心放在三分线交点附近，并为视线或动作方向保留合理空间',
      sortOrder: 10,
    },
    {
      id: 'module-composition-centered',
      label: '中心构图',
      prompt: '采用中心构图，将主要主体稳定放置在画面中心，周围视觉元素保持均衡并服务于中心焦点',
      sortOrder: 20,
    },
    {
      id: 'module-composition-symmetry',
      label: '对称构图',
      prompt: '采用严格对称构图，以明确中轴组织左右画面元素，保持结构、重量和留白的视觉平衡',
      sortOrder: 30,
    },
    {
      id: 'module-composition-diagonal',
      label: '对角线构图',
      prompt: '采用对角线构图，让主体轮廓、动作或环境线条沿画面对角方向展开，形成清晰动态引导',
      sortOrder: 40,
    },
    {
      id: 'module-composition-negative',
      label: '大面积留白',
      prompt: '使用大面积负空间构图，将主体安排在画面局部区域，其余区域保持简洁留白并避免杂乱元素',
      sortOrder: 50,
    },
    {
      id: 'module-composition-golden-ratio',
      label: '黄金分割',
      prompt: '采用黄金分割构图，将主要视觉中心或关键边界安排在画面约零点三八二或零点六一八的位置',
      sortOrder: 60,
    },
    {
      id: 'module-composition-golden-spiral',
      label: '黄金螺旋',
      prompt: '采用黄金螺旋构图，让外围元素沿收缩曲线逐步引导视线，并将主要焦点放在螺旋收束处',
      sortOrder: 70,
    },
    {
      id: 'module-composition-frame-within-frame',
      label: '框中框',
      prompt: '采用框中框构图，利用画面内明确的边缘结构围合主要主体，形成完整内框并保留外层空间',
      sortOrder: 80,
    },
    {
      id: 'module-composition-leading-lines',
      label: '引导线',
      prompt: '采用引导线构图，组织一条或多条可追踪线条从画面边缘延伸，并在主要主体附近汇合或结束',
      sortOrder: 90,
    },
    {
      id: 'module-composition-triangle',
      label: '三角构图',
      prompt: '采用三角构图，将三个主要视觉节点组织成边界清楚的三角形，使主体关系稳定且层级明确',
      sortOrder: 100,
    },
    {
      id: 'module-composition-radial',
      label: '放射构图',
      prompt: '采用放射构图，使主要线条、轮廓或重复元素围绕同一中心向外展开，形成清楚的辐射秩序',
      sortOrder: 110,
    },
    {
      id: 'module-composition-s-curve',
      label: '曲线构图',
      prompt: '采用曲线构图，让主要视觉路径沿连续的之形曲线穿过画面，在转折处依次连接关键元素',
      sortOrder: 120,
    },
    {
      id: 'module-composition-horizontal-layers',
      label: '水平分层',
      prompt: '采用水平分层构图，将画面组织为高度不同的上下带状区域，各层边界清楚且视觉权重有序递进',
      sortOrder: 130,
    },
    {
      id: 'module-composition-vertical-columns',
      label: '垂直分栏',
      prompt: '采用垂直分栏构图，以两条或多条纵向边界划分画面，各栏宽度与元素密度形成明确层级',
      sortOrder: 140,
    },
    {
      id: 'module-composition-depth-layers',
      label: '空间分层',
      prompt: '采用空间分层构图，以局部遮挡和尺度递进组织前部、中部与后部元素，使三个层次清楚分离',
      sortOrder: 150,
    },
    {
      id: 'module-composition-repetition',
      label: '重复韵律',
      prompt: '采用重复韵律构图，将相似形状按稳定间距连续排列，并通过一次间距或方向变化建立视觉重点',
      sortOrder: 160,
    },
    {
      id: 'module-composition-odd-group',
      label: '奇数组团',
      prompt: '采用奇数组团构图，将三个或五个主要单元组织成紧密整体，避免平均对半分组和机械镜像排列',
      sortOrder: 170,
    },
    {
      id: 'module-composition-asymmetric-balance',
      label: '非对称平衡',
      prompt: '采用非对称平衡构图，让不同大小或数量的元素分处画面两侧，通过距离与视觉重量取得均衡',
      sortOrder: 180,
    },
    {
      id: 'module-composition-circular',
      label: '环形构图',
      prompt: '采用环形构图，让主要元素围绕中央区域形成闭合或近似闭合的视觉回路，避免路径在边缘中断',
      sortOrder: 190,
    },
    {
      id: 'module-composition-z-path',
      label: '之字路径',
      prompt: '采用之字路径构图，使视线从画面上部一侧横向移动，再斜穿中央并到达下部另一侧',
      sortOrder: 200,
    },
    {
      id: 'module-composition-scatter',
      label: '散点构图',
      prompt: '采用散点构图，将多个同级元素分散布置在画面各区域，以受控间距维持整体均衡并避免局部拥堵',
      sortOrder: 210,
    },
    {
      id: 'module-composition-grid',
      label: '网格构图',
      prompt: '采用网格构图，将多个元素对齐到规则行列，统一单元尺寸、间隔和外边距，形成清晰排列秩序',
      sortOrder: 220,
    },
  ],
} satisfies PromptModuleAssetDefinition
