import type { PromptModuleAssetDefinition } from './types'

export default {
  category: {
    key: 'environment',
    label: '场景',
    description: '短名称用于选择，实际组合时注入完整空间约束',
    selectionMode: 'single',
    maxSelections: 1,
  },
  modules: [
    {
      id: 'module-environment-studio',
      label: '极简影棚',
      prompt: '主体置于干净的极简摄影棚内，使用连续无缝背景，环境元素克制且不分散主体注意力',
      sortOrder: 10,
    },
    {
      id: 'module-environment-interior',
      label: '窗边室内',
      prompt: '主体位于靠近大型窗户的室内空间，窗框与少量家具建立真实尺度和清晰空间层次',
      sortOrder: 20,
    },
    {
      id: 'module-environment-city',
      label: '城市街道',
      prompt: '主体置于真实城市街道环境中，建筑立面、道路设施、路面标记与街区纵深提供明确都市语境',
      sortOrder: 30,
    },
    {
      id: 'module-environment-nature',
      label: '自然旷野',
      prompt: '主体置于开阔自然旷野，地表、远景与天空形成清晰纵深，避免无关人造物干扰',
      sortOrder: 40,
    },
    {
      id: 'module-environment-rain',
      label: '雨天',
      prompt: '场景处于持续降雨天气，空气中保留方向一致的雨丝，远近区域的雨量和能见度变化自然',
      sortOrder: 50,
    },
    {
      id: 'module-environment-bamboo',
      label: '层叠竹林',
      prompt: '设置为层叠竹林环境，近处竹节与落叶、中段密集竹秆、远处林隙共同建立连续纵深',
      sortOrder: 60,
    },
    {
      id: 'module-environment-alpine-lake',
      label: '高山湖岸',
      prompt: '设置为高山湖岸环境，裸岩、低矮植被、平静水面与远处山脊构成明确地貌层次',
      sortOrder: 70,
    },
    {
      id: 'module-environment-coastal-cliff',
      label: '海岸峭壁',
      prompt: '设置为海岸峭壁环境，风蚀岩层、浪花、潮湿礁石与远方海平线共同界定空间尺度',
      sortOrder: 80,
    },
    {
      id: 'module-environment-dunes',
      label: '连绵沙丘',
      prompt: '设置为连绵沙丘环境，以风纹沙脊、稀疏耐旱植物和远处起伏地平线形成开阔层次',
      sortOrder: 90,
    },
    {
      id: 'module-environment-snow-forest',
      label: '积雪针叶林',
      prompt: '设置为积雪针叶林环境，雪覆地表、密集树干、折断枝条与远处林线呈现寒地生态细节',
      sortOrder: 100,
    },
    {
      id: 'module-environment-wetland',
      label: '浅水湿地',
      prompt: '设置为浅水湿地环境，芦苇群、泥滩、水道与低矮草洲交错分布，空间边界自然延伸',
      sortOrder: 110,
    },
    {
      id: 'module-environment-limestone-cave',
      label: '石灰岩洞',
      prompt: '设置为石灰岩洞穴环境，钟乳石、石笋、湿润岩壁和地下水洼构成立体封闭空间',
      sortOrder: 120,
    },
    {
      id: 'module-environment-workshop',
      label: '工业车间',
      prompt: '设置为工业车间环境，钢梁、管线、操作平台和磨损地面按真实功能关系组织空间',
      sortOrder: 130,
    },
    {
      id: 'module-environment-greenhouse',
      label: '玻璃温室',
      prompt: '设置为玻璃温室环境，金属骨架、种植台、攀援植物与通行步道形成清晰内部结构',
      sortOrder: 140,
    },
    {
      id: 'module-environment-gallery',
      label: '当代展厅',
      prompt: '设置为当代展厅环境，连续展墙、展台、导视标识与宽阔通道保持克制有序的空间关系',
      sortOrder: 150,
    },
    {
      id: 'module-environment-rooftop',
      label: '城市屋顶',
      prompt: '设置为城市屋顶平台环境，女儿墙、通风设备、检修通道与远处建筑天际线建立高度感',
      sortOrder: 160,
    },
    {
      id: 'module-environment-courtyard',
      label: '传统院落',
      prompt: '设置为传统院落环境，围合墙面、木构廊道、石质铺地与少量庭院植物呈现明确空间层级',
      sortOrder: 170,
    },
    {
      id: 'module-environment-indoor-generic',
      label: '一般室内',
      prompt: '场景位于具有完整墙面、顶面和地面的室内空间，入口、通道与家具关系符合真实使用逻辑',
      sortOrder: 180,
    },
    {
      id: 'module-environment-urban-generic',
      label: '城市户外',
      prompt: '场景位于城市户外空间，建筑边界、道路或公共设施共同建立明确的人造环境语境',
      sortOrder: 190,
    },
    {
      id: 'module-environment-natural-generic',
      label: '自然环境',
      prompt: '场景以自然地貌、植被、水体或岩层为主要空间构成，不让无关人造设施主导画面',
      sortOrder: 200,
    },
    {
      id: 'module-environment-semi-outdoor',
      label: '半室外空间',
      prompt: '场景位于有顶盖或围合边界但仍与室外连通的半室外空间，内外区域关系清楚',
      sortOrder: 210,
    },
    {
      id: 'module-environment-alley',
      label: '城市街巷',
      prompt: '设置为尺度较窄的城市街巷，两侧连续立面、路面设施和纵深出口共同界定线性空间',
      sortOrder: 220,
    },
    {
      id: 'module-environment-time-dawn',
      label: '黎明时段',
      prompt: '场景时间设定在日出前后，天空刚开始变亮，环境仍保留清晨的低照度状态',
      sortOrder: 230,
    },
    {
      id: 'module-environment-time-day',
      label: '日间',
      prompt: '场景时间设定在普通日间，环境拥有充分可见度，不附加黎明、黄昏或夜间特征',
      sortOrder: 240,
    },
    {
      id: 'module-environment-time-noon',
      label: '正午时段',
      prompt: '场景时间设定在太阳接近最高点的正午，时间特征明确且不混入清晨或黄昏迹象',
      sortOrder: 250,
    },
    {
      id: 'module-environment-time-dusk',
      label: '黄昏时段',
      prompt: '场景时间设定在日落前后，地平线附近仍有残留天光，环境逐步进入低照度状态',
      sortOrder: 260,
    },
    {
      id: 'module-environment-time-blue-hour',
      label: '蓝调时刻',
      prompt: '场景时间设定在太阳已越过地平线而天空仍有余亮的蓝调时刻，自然环境亮度低而未全黑',
      sortOrder: 270,
    },
    {
      id: 'module-environment-time-night',
      label: '夜间',
      prompt: '场景时间设定为夜间，天空和未受照环境保持低亮度，人工光源或月光成为主要可见照明来源',
      sortOrder: 280,
    },
    {
      id: 'module-environment-weather-clear',
      label: '晴朗天气',
      prompt: '场景处于晴朗天气，空气能见度良好，不出现降雨、降雪、浓雾或厚重低云',
      sortOrder: 290,
    },
    {
      id: 'module-environment-weather-overcast',
      label: '阴天',
      prompt: '场景上空被连续云层覆盖，天气保持阴天状态，不出现清晰直射阳光或明显晴空区域',
      sortOrder: 300,
    },
    {
      id: 'module-environment-weather-snow',
      label: '降雪',
      prompt: '场景处于持续降雪天气，雪花大小和运动方向自然，远处能见度随降雪密度适度下降',
      sortOrder: 310,
    },
    {
      id: 'module-environment-weather-fog',
      label: '薄雾',
      prompt: '场景中存在均匀薄雾，远处对比度和清晰度逐级下降，近处主体边缘仍保持可辨',
      sortOrder: 320,
    },
    {
      id: 'module-environment-ground-wet',
      label: '湿润地面',
      prompt: '地面处于均匀湿润状态，低洼处可见少量积水，反射强度随表面粗糙度自然变化',
      sortOrder: 330,
    },
    {
      id: 'module-environment-scale-enclosed',
      label: '封闭尺度',
      prompt: '空间边界靠近主体并形成明显围合，远处出口较少，整体呈现封闭尺度',
      sortOrder: 340,
    },
    {
      id: 'module-environment-scale-compact',
      label: '紧凑尺度',
      prompt: '空间尺度紧凑但仍可活动，主体与主要边界距离较近，各区域功能关系清楚',
      sortOrder: 350,
    },
    {
      id: 'module-environment-scale-open',
      label: '开阔尺度',
      prompt: '空间向多个方向连续展开，主体与远处边界之间保留大范围可见距离',
      sortOrder: 360,
    },
    {
      id: 'module-environment-scale-monumental',
      label: '宏大尺度',
      prompt: '环境尺度显著大于主要主体，以巨大的空间跨度或结构体量建立清晰尺度对比',
      sortOrder: 370,
    },
    {
      id: 'module-environment-density-minimal',
      label: '极简环境',
      prompt: '环境仅保留定义空间所需的最少元素，不增加与主体、地点或事件无关的装饰物',
      sortOrder: 380,
    },
    {
      id: 'module-environment-density-controlled',
      label: '克制环境',
      prompt: '环境信息保持克制，少量辅助元素用于说明地点和尺度，但不与主体竞争视觉注意力',
      sortOrder: 390,
    },
    {
      id: 'module-environment-density-natural',
      label: '自然丰富',
      prompt: '环境包含符合地点逻辑的丰富细节，元素密度自然变化，并保持主要空间结构可读',
      sortOrder: 400,
    },
    {
      id: 'module-environment-density-dense',
      label: '高密环境',
      prompt: '环境包含高密度但有组织的物件、结构或自然元素，避免随机堆叠和不可读的局部混乱',
      sortOrder: 410,
    },
  ],
} satisfies PromptModuleAssetDefinition
