import type { PromptModuleAssetDefinition } from './types'

export default {
  category: {
    key: 'expression',
    label: '表情与视线',
    description: '可组合一个表情和一个视线方向，实际注入完整面部指令',
    selectionMode: 'multiple',
    maxSelections: 2,
  },
  modules: [
    {
      id: 'module-expression-camera',
      label: '直视镜头',
      prompt: '人物双眼目光明确对准镜头，与观看者建立直接视觉联系，双眼方向保持一致',
      sortOrder: 10,
      selectionGroup: 'gaze',
    },
    {
      id: 'module-expression-offscreen',
      label: '看向画外',
      prompt: '人物目光自然投向画面之外，视线方向清晰统一，不与镜头发生直接对视',
      sortOrder: 20,
      selectionGroup: 'gaze',
    },
    {
      id: 'module-expression-calm',
      label: '平静',
      prompt: '人物保持平静克制的面部神情，眉眼放松、嘴角自然，不表现夸张情绪',
      sortOrder: 30,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-smile',
      label: '轻微微笑',
      prompt: '人物呈现自然且轻微的微笑，嘴角小幅上扬，眼神柔和，避免僵硬或过度夸张',
      sortOrder: 40,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-serious',
      label: '严肃',
      prompt: '人物呈现专注严肃的面部神情，眉眼收敛、嘴唇自然闭合，情绪明确但不过度愤怒',
      sortOrder: 50,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-downward-gaze',
      label: '垂眼下视',
      prompt: '人物双眼视线落向自身下方近处，瞳孔方向一致，不与镜头或画外远处建立对视',
      sortOrder: 60,
      selectionGroup: 'gaze',
    },
    {
      id: 'module-expression-upward-gaze',
      label: '抬眼上视',
      prompt: '人物双眼视线抬向头部上方，瞳孔靠近上眼睑且方向一致，头部朝向保持独立',
      sortOrder: 70,
      selectionGroup: 'gaze',
    },
    {
      id: 'module-expression-eyes-closed',
      label: '闭眼',
      prompt: '人物双眼自然闭合，上下眼睑完整贴合且左右一致，不保留任何明确视线方向',
      sortOrder: 80,
      selectionGroup: 'gaze',
    },
    {
      id: 'module-expression-in-frame-gaze',
      label: '注视画内',
      prompt: '人物双眼明确注视画面内可见对象，瞳孔汇聚方向与目标位置一致，不直视镜头',
      sortOrder: 90,
      selectionGroup: 'gaze',
    },
    {
      id: 'module-expression-mutual-gaze',
      label: '相互对视',
      prompt: '人物目光锁定画面内另一主体的眼部或面部，双眼方向统一并形成清楚对视关系',
      sortOrder: 100,
      selectionGroup: 'gaze',
    },
    {
      id: 'module-expression-sidelong-gaze',
      label: '侧目而视',
      prompt: '人物头部朝向基本不变，仅将双眼瞳孔移向一侧，形成明确的侧向注视',
      sortOrder: 110,
      selectionGroup: 'gaze',
    },
    {
      id: 'module-expression-unfocused-gaze',
      label: '目光失焦',
      prompt: '人物双眼保持睁开但不锁定具体目标，瞳孔方向近似平行，呈现失焦的空泛视线',
      sortOrder: 120,
      selectionGroup: 'gaze',
    },
    {
      id: 'module-expression-laughter',
      label: '开怀大笑',
      prompt: '人物呈现开怀大笑，嘴巴自然张开，嘴角明显上扬，面颊抬高并形成清楚笑纹',
      sortOrder: 130,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-sadness',
      label: '悲伤',
      prompt: '人物呈现明确悲伤神情，眉毛内侧上扬，面颊失去张力，嘴角自然向下收拢',
      sortOrder: 140,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-anger',
      label: '愤怒',
      prompt: '人物呈现克制而明确的愤怒，眉毛向内下压，下颌收紧，嘴唇紧闭或用力抿住',
      sortOrder: 150,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-surprise',
      label: '惊讶',
      prompt: '人物呈现突然惊讶的神情，双眉明显抬高，额部拉伸，嘴唇自然张开形成小幅圆形',
      sortOrder: 160,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-fear',
      label: '恐惧',
      prompt: '人物呈现紧张恐惧的神情，眉毛内侧抬高并靠拢，鼻翼与嘴角收紧，嘴唇微张',
      sortOrder: 170,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-shyness',
      label: '害羞',
      prompt: '人物呈现含蓄害羞的神情，面颊轻微泛红，眉部放松，嘴唇轻抿并保持收敛',
      sortOrder: 180,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-disgust',
      label: '厌恶',
      prompt: '人物呈现明确厌恶神情，鼻梁轻皱，上唇一侧抬起，眉间收紧且嘴角略微后撤',
      sortOrder: 190,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-confusion',
      label: '困惑',
      prompt: '人物呈现疑惑不解的神情，一侧眉毛高于另一侧，眉间轻皱，嘴唇保持不对称',
      sortOrder: 200,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-anxiety',
      label: '焦虑',
      prompt: '人物呈现持续焦虑的神情，眉毛向内靠拢，面颊与下颌紧绷，嘴唇用力抿合',
      sortOrder: 210,
      selectionGroup: 'emotion',
    },
    {
      id: 'module-expression-fatigue',
      label: '疲惫',
      prompt: '人物呈现明显疲惫状态，面部肌肉松弛，眉尾下垂，嘴角与下颌缺乏主动张力',
      sortOrder: 220,
      selectionGroup: 'emotion',
    },
  ],
} satisfies PromptModuleAssetDefinition
