import type { PromptModuleAssetDefinition } from './types'

export default {
  category: {
    key: 'lighting',
    label: '光线',
    description: '短名称用于选择，实际组合时注入光源方向与明暗关系',
    selectionMode: 'single',
    maxSelections: 1,
  },
  modules: [
    {
      id: 'module-lighting-window',
      label: '窗户自然光',
      prompt: '使用穿过窗户进入场景的自然光作为主要光源，窗洞位置和光线传播方向保持一致',
      sortOrder: 10,
    },
    {
      id: 'module-lighting-backlight',
      label: '侧后方向',
      prompt: '主光从主体侧后方照射，使受光边缘与背光正面形成明确方向关系，不在此项中限定光质软硬',
      sortOrder: 20,
    },
    {
      id: 'module-lighting-studio',
      label: '影棚灯光',
      prompt: '使用可控影棚灯具作为主要照明来源，光源位置、输出强度和修光附件均可独立调整',
      sortOrder: 30,
    },
    {
      id: 'module-lighting-neon',
      label: '彩色霓虹光',
      prompt: '使用有明确色相的霓虹或发光标识作为照明来源，彩色光只影响实际受光表面和邻近环境',
      sortOrder: 40,
    },
    {
      id: 'module-lighting-dramatic',
      label: '戏剧聚光',
      prompt: '使用方向明确的局部硬质聚光照亮主体关键区域，背景压暗，形成高反差戏剧明暗结构',
      sortOrder: 50,
    },
    {
      id: 'module-lighting-overhead-soft',
      label: '顶部方向',
      prompt: '主光从主体正上方垂直落下，顶部受光区域最明确，阴影方向朝下方延伸',
      sortOrder: 60,
    },
    {
      id: 'module-lighting-frontal-soft',
      label: '正面方向',
      prompt: '主光从镜头附近的正前方向照射主体，受光面大致面向摄影机，侧向阴影较少',
      sortOrder: 70,
    },
    {
      id: 'module-lighting-split',
      label: '正侧方向',
      prompt: '主光从主体水平侧方约九十度位置照射，使面向光源的一侧受光，另一侧进入背光区域',
      sortOrder: 80,
    },
    {
      id: 'module-lighting-upper-side',
      label: '侧前上方',
      prompt: '主光从主体侧前上方约四十五度位置照射，同时形成横向和纵向的明暗转折',
      sortOrder: 90,
    },
    {
      id: 'module-lighting-top-front',
      label: '正前上方',
      prompt: '主光从主体正前上方三十至四十五度位置向下照射，正面和顶部共同获得照明',
      sortOrder: 100,
    },
    {
      id: 'module-lighting-underlight',
      label: '底部方向',
      prompt: '主光从主体下方向上照射，使下侧表面先受光，并形成与常规顶部照明相反的阴影方向',
      sortOrder: 110,
    },
    {
      id: 'module-lighting-overcast',
      label: '阴天漫射',
      prompt: '阴天漫射光从整个上半球均匀包围，方向性较弱、阴影极软，环境光比接近二比一',
      sortOrder: 120,
    },
    {
      id: 'module-lighting-noon',
      label: '正午直射',
      prompt: '正午直射光从近乎垂直的高位落下，光质坚硬、阴影短而清晰，光比保持六比一',
      sortOrder: 130,
    },
    {
      id: 'module-lighting-dawn',
      label: '黎明低光',
      prompt: '黎明时的低角度光从单侧地平线方向掠入，光质偏软、阴影较长，光比约为三比一',
      sortOrder: 140,
    },
    {
      id: 'module-lighting-afterglow',
      label: '暮后天光',
      prompt: '日落后保留来自天空顶部的大范围残照，光质极软、方向微弱，整体反差不超过二比一',
      sortOrder: 150,
    },
    {
      id: 'module-lighting-low-point',
      label: '低位点光',
      prompt: '小型点光源从侧前方低位照射，光质偏硬且衰减迅速，近处与远处亮度形成五比一反差',
      sortOrder: 160,
    },
    {
      id: 'module-lighting-blinds',
      label: '百叶条光',
      prompt: '硬光从单侧穿过狭窄平行缝隙，投下边缘清晰的条带阴影，受光与遮蔽区域约六比一',
      sortOrder: 170,
    },
    {
      id: 'module-lighting-daylight',
      label: '自然日光',
      prompt: '使用太阳与天空共同形成的自然日光作为主要照明来源，光线变化符合室外时间和天气条件',
      sortOrder: 180,
    },
    {
      id: 'module-lighting-soft-quality',
      label: '柔和光质',
      prompt: '使用相对主体尺寸较大的光源形成柔和光质，阴影边缘平缓，明暗过渡连续',
      sortOrder: 190,
    },
    {
      id: 'module-lighting-medium-quality',
      label: '中等光质',
      prompt: '使用中等表观尺寸光源，阴影边缘具有可辨过渡，既不完全柔化也不形成锐利硬边',
      sortOrder: 200,
    },
    {
      id: 'module-lighting-hard-quality',
      label: '硬质光线',
      prompt: '使用相对主体尺寸较小的光源形成硬质光线，阴影边缘清楚，局部明暗分界明确',
      sortOrder: 210,
    },
    {
      id: 'module-lighting-low-contrast',
      label: '低反差',
      prompt: '控制受光区与阴影区亮度差异，使暗部保留充分信息，整体明暗反差保持较低',
      sortOrder: 220,
    },
    {
      id: 'module-lighting-medium-contrast',
      label: '中等反差',
      prompt: '保持受光区与阴影区之间的中等亮度差异，暗部可读，同时保留明确立体塑形',
      sortOrder: 230,
    },
    {
      id: 'module-lighting-high-contrast',
      label: '高反差',
      prompt: '扩大受光区与阴影区的亮度差异，保留明确高光和深暗区域，形成强烈明暗结构',
      sortOrder: 240,
    },
    {
      id: 'module-lighting-rim',
      label: '轮廓辅助光',
      prompt: '在主体侧后方增加窄幅辅助光，仅勾勒外缘并帮助主体与背景分离，不取代主要光源',
      sortOrder: 250,
    },
  ],
} satisfies PromptModuleAssetDefinition
