import type { PromptModuleAssetDefinition } from './types'

export default {
  category: {
    key: 'subject',
    label: '主体',
    description: '定义主体数量、类型或入镜方式',
    selectionMode: 'single',
    maxSelections: 1,
  },
  modules: [
    {
      id: 'module-subject-single',
      label: '单主体',
      prompt: '画面中仅设置一个清晰可辨的主要主体，不复制该主体，也不增加竞争主要地位的第二主体',
      sortOrder: 10,
    },
    {
      id: 'module-subject-pair',
      label: '双主体',
      prompt: '画面中设置两个主要主体，二者外形边界、相对尺度和空间位置均保持清楚可辨',
      sortOrder: 20,
    },
    {
      id: 'module-subject-group',
      label: '小型群体',
      prompt: '画面中设置三至五个主要主体形成小型群体，每个主体轮廓可辨且前后遮挡关系清楚',
      sortOrder: 30,
    },
    {
      id: 'module-subject-back',
      label: '背向镜头',
      prompt: '主体背面朝向镜头所在方向，正面主要识别区域不可见，背部轮廓和朝向保持清楚',
      sortOrder: 40,
    },
    {
      id: 'module-subject-hands',
      label: '仅手部',
      prompt: '画面仅展示人物手部与手腕区域，不出现面部或躯干，手指数量与关节结构必须自然准确',
      sortOrder: 50,
    },
    {
      id: 'module-subject-crowd',
      label: '大型群体',
      prompt: '画面中设置六个以上主体形成大型群体，个体分布彼此可分辨，前后遮挡关系清楚',
      sortOrder: 60,
    },
    {
      id: 'module-subject-front-facing',
      label: '正面入镜',
      prompt: '主体正面朝向镜头所在方向，左右结构近似对称，主要识别特征完整可见',
      sortOrder: 70,
    },
    {
      id: 'module-subject-profile',
      label: '侧面入镜',
      prompt: '主体以严格九十度侧面朝向入镜，仅呈现一侧轮廓，避免出现近似正面的双侧特征',
      sortOrder: 80,
    },
    {
      id: 'module-subject-three-quarter',
      label: '三分侧面',
      prompt: '主体相对镜头旋转约三十至四十五度，同时保留正面结构与一侧轮廓特征',
      sortOrder: 90,
    },
    {
      id: 'module-subject-face-obscured',
      label: '遮面入镜',
      prompt: '主体的面部或核心识别区域被完全遮住，仅通过外轮廓与可见局部保留身份线索',
      sortOrder: 100,
    },
    {
      id: 'module-subject-edge-entry',
      label: '边缘入镜',
      prompt: '主体从画面边缘部分进入，仅保留明确可辨的局部，未入镜部分自然延伸至画框之外',
      sortOrder: 110,
    },
    {
      id: 'module-subject-feet-only',
      label: '仅脚部',
      prompt: '画面仅展示人物双脚及脚踝区域，不出现上半身，双脚数量、朝向与承重关系准确',
      sortOrder: 120,
    },
    {
      id: 'module-subject-animal',
      label: '动物主体',
      prompt: '以动物作为主要视觉主体，物种形态与肢体结构清晰，不将其转换为人类外观',
      sortOrder: 130,
    },
    {
      id: 'module-subject-object',
      label: '物件主体',
      prompt: '以物品作为主要视觉主体，不安排人物抢占主体地位，物体外形与部件关系明确',
      sortOrder: 140,
    },
    {
      id: 'module-subject-plant',
      label: '植物主体',
      prompt: '以植物作为主要视觉主体，枝干、叶片或花朵从属关系明确，不出现拟人化肢体',
      sortOrder: 150,
    },
    {
      id: 'module-subject-architecture',
      label: '建筑主体',
      prompt: '以建筑体作为主要视觉主体，主体轮廓完整可读，结构轴线与体块关系保持一致',
      sortOrder: 160,
    },
    {
      id: 'module-subject-creature',
      label: '虚构生物',
      prompt: '以虚构生物作为主要视觉主体，固定其物种特征、肢体数量与身体连接方式',
      sortOrder: 170,
    },
    {
      id: 'module-subject-person',
      label: '人物主体',
      prompt: '以人物作为主要视觉主体，保持真实一致的人体结构、身份特征和身体部位连接关系',
      sortOrder: 180,
    },
    {
      id: 'module-subject-interaction-conversation',
      label: '交谈关系',
      prompt: '多个主体之间形成明确交谈关系，身体朝向、距离和注意力共同指向正在进行的交流',
      sortOrder: 190,
    },
    {
      id: 'module-subject-interaction-cooperation',
      label: '协作关系',
      prompt: '多个主体围绕同一任务形成协作关系，动作分工清楚，并共享可辨识的操作目标',
      sortOrder: 200,
    },
    {
      id: 'module-subject-interaction-opposition',
      label: '对立关系',
      prompt: '多个主体形成明确对立关系，彼此朝向和空间距离体现张力，但肢体结构不发生混叠',
      sortOrder: 210,
    },
    {
      id: 'module-subject-interaction-parallel',
      label: '并列关系',
      prompt: '多个主体以并列关系共同出现，各自主体地位接近，排列有序且不强制发生互动',
      sortOrder: 220,
    },
  ],
} satisfies PromptModuleAssetDefinition
