import type { PromptTemplate } from '@/types'
import {
  createBuiltinPromptTemplate,
  createRequiredVariable,
} from './createPromptTemplate'

export const EXPERIMENTAL_ABSTRACT_TEMPLATES: PromptTemplate[] = [
  createBuiltinPromptTemplate({
    id: 'tpl-22',
    title: '超现实场景合成',
    summary: '把真实元素组合成具有单一清晰概念的不可能场景。',
    content: '创作一幅超现实场景：{{subject}}与{{impossibleRelationship}}形成视觉核心，环境位于{{environment}}。所有元素保持写实材质、统一透视和一致光源，让不可能关系看起来真实可信；使用{{viewpoint}}建立明确尺度，背景简洁并为主体留出呼吸空间。整体情绪为{{mood}}，色彩和阴影自然连续，只保留一个核心悖论，不堆叠无关奇观，不出现结构破碎、重复主体、随机文字或水印。',
    categoryId: 'experimental-abstract',
    medium: 'photography',
    styleIds: ['surreal', 'realistic', 'minimal'],
    variables: [
      createRequiredVariable('subject', '现实主体', '例如：一艘白色帆船', '一艘白色帆船'),
      createRequiredVariable('impossibleRelationship', '不可能关系', '例如：在巨大的透明水滴内部航行', '在巨大的透明水滴内部航行'),
      createRequiredVariable('environment', '环境', '例如：无边的干燥盐湖', '无边的干燥盐湖'),
      createRequiredVariable('viewpoint', '观察视角', '例如：远距离平视宽幅构图', '远距离平视宽幅构图'),
      createRequiredVariable('mood', '情绪', '例如：安静、陌生而明亮', '安静、陌生而明亮'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-23',
    title: '流体材质实验',
    summary: '以材质变化、光线和运动轨迹构建抽象三维视觉。',
    content: '创作一幅以{{material}}为核心的抽象3D材质实验，运动形态为{{motion}}。主体悬浮在纯净空间中，由连续曲面和少量分离液滴构成，厚度、表面张力和重力关系可信；使用{{lighting}}揭示透明度、粗糙度和边缘高光，背景采用{{backgroundColor}}，并以{{accentColor}}形成有限色彩对比。构图集中、细节精致，不加入人物、产品、文字、标志、杂乱粒子或不一致的材质反射。',
    categoryId: 'experimental-abstract',
    medium: 'three-dimensional',
    styleIds: ['abstract', 'surreal', 'minimal'],
    variables: [
      createRequiredVariable('material', '实验材质', '例如：半透明虹彩玻璃液体', '半透明虹彩玻璃液体'),
      createRequiredVariable('motion', '运动形态', '例如：向上扭转并形成环形波峰', '向上扭转并形成环形波峰'),
      createRequiredVariable('lighting', '布光', '例如：顶部大面积柔光与侧后窄光', '顶部大面积柔光与侧后窄光'),
      createRequiredVariable('backgroundColor', '背景色', '例如：深石墨灰', '深石墨灰'),
      createRequiredVariable('accentColor', '点缀色', '例如：电光蓝与少量洋红', '电光蓝与少量洋红'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-24',
    title: '抽象几何秩序',
    summary: '使用有限图形、比例和色彩节奏建立现代抽象画面。',
    content: '围绕{{concept}}创作一幅现代抽象几何作品，以{{shapes}}作为主要视觉元素。采用{{composition}}控制比例、留白和视觉节奏，形状之间只发生清晰的切割、叠加或对齐关系；使用{{palette}}，表面包含轻微纸张颗粒和有限的印刷套色偏差，保持平面性与手工触感。画面简洁但不空洞，不加入具象人物、风景、三维光影、装饰文字、现成标志或水印。',
    categoryId: 'experimental-abstract',
    medium: 'graphic-design',
    styleIds: ['abstract', 'minimal', 'retro'],
    variables: [
      createRequiredVariable('concept', '抽象概念', '例如：稳定与失衡', '稳定与失衡'),
      createRequiredVariable('shapes', '主要形状', '例如：圆、窄长矩形与断开的弧线', '圆、窄长矩形与断开的弧线'),
      createRequiredVariable('composition', '构图秩序', '例如：左下聚集、右上大面积留白', '左下聚集、右上大面积留白'),
      createRequiredVariable('palette', '配色', '例如：砖红、钴蓝、黑色与暖白', '砖红、钴蓝、黑色与暖白'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-60',
    title: '手绘形态变异',
    summary: '让熟悉对象在连续画面中逐步转化为抽象生命形态。',
    content: '以{{startingObject}}为起点创作手绘形态变异作品，使其经过{{transformationStages}}逐步转化为{{finalForm}}。采用连续但不完全对称的构图，让材质、轮廓和内部结构在每一阶段都有可追踪的变化；使用{{drawingTechnique}}和{{palette}}，保留纸张、擦除、叠线与颜料渗化痕迹。作品应具有生物般的内在逻辑而非随机扭曲，不加入背景叙事、摄影写实、现成角色、可读文字或水印。',
    categoryId: 'experimental-abstract',
    medium: 'illustration',
    styleIds: ['surreal', 'abstract', 'natural'],
    variables: [
      createRequiredVariable('startingObject', '起始对象', '例如：一枚干燥的松果'),
      createRequiredVariable('transformationStages', '变化过程', '例如：鳞片展开、内部发芽并形成柔软触须'),
      createRequiredVariable('finalForm', '最终形态', '例如：漂浮的半透明种子生物'),
      createRequiredVariable('drawingTechnique', '绘制技法', '例如：石墨叠线、稀释墨水与半透明水彩'),
      createRequiredVariable('palette', '配色', '例如：炭黑、苔绿与微弱荧光黄'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-61',
    title: '材质炼金渲染',
    summary: '探索两种材质融合时的高端、陌生且可信的视觉状态。',
    content: '创作一件以{{materialPair}}融合为主题的抽象3D材质雕塑，变化机制是{{transformationRule}}。主体悬置于{{environment}}中，形态由稳定几何逐渐过渡到流动表面，微观纹理、反射、折射与厚度关系符合物理逻辑；使用{{lighting}}勾勒材质边界和内部层次，构图极简并保留高级品牌视觉所需留白。画面陌生但不脏乱，不生成廉价塑料、无意义碎片、文字、标志或水印。',
    categoryId: 'experimental-abstract',
    medium: 'three-dimensional',
    styleIds: ['luxury', 'surreal', 'abstract'],
    variables: [
      createRequiredVariable('materialPair', '材质组合', '例如：液态黑曜石与半透明织物'),
      createRequiredVariable('transformationRule', '变化规则', '例如：坚硬表面沿纤维方向逐渐变得柔软'),
      createRequiredVariable('environment', '环境', '例如：无边界的深灰镜面空间'),
      createRequiredVariable('lighting', '光线', '例如：顶部冷色长条光与低位暖色反射'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-62',
    title: '故障字体实验海报',
    summary: '通过可控错位、切片和重组探索字体的动态边界。',
    content: '围绕{{wordConcept}}设计故障字体实验海报，以{{distortionMethod}}重组一个大型文字占位轮廓。保持基础字形的主要识别骨架，同时让局部切片、扫描线和位移形成{{visualRhythm}}，使用{{palette}}和严格网格控制混乱程度；辅助信息只占画面很小区域，并以规则线块表示。作品应像经过设计的字体研究而非软件报错，不生成随机乱码、密集小字、游戏界面、现成品牌标志或水印。',
    categoryId: 'experimental-abstract',
    medium: 'graphic-design',
    styleIds: ['typographic', 'abstract', 'science-fiction'],
    variables: [
      createRequiredVariable('wordConcept', '文字概念', '例如：延迟'),
      createRequiredVariable('distortionMethod', '变形方法', '例如：水平扫描切片与局部字符回声'),
      createRequiredVariable('visualRhythm', '视觉节奏', '例如：从左侧稳定逐渐向右侧失真'),
      createRequiredVariable('palette', '配色', '例如：黑色、荧光绿与少量品红'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-63',
    title: '强制透视人体摄影',
    summary: '利用空间尺度错觉创造可信而不依赖后期拼贴的画面。',
    content: '在{{location}}拍摄强制透视人体作品，让{{subject}}与{{spatialElement}}形成{{scaleIllusion}}。精确安排相机位置、前后景距离和人物姿态，使错觉从单一视点成立，同时保留真实接触阴影、透视线和环境材质；使用{{lightingCondition}}与较深景深，让前后元素都足够清楚。效果应来自现场构图而非粗糙拼贴，不出现人物畸形、错误遮挡、不一致光线、多余肢体、文字或水印。',
    categoryId: 'experimental-abstract',
    medium: 'photography',
    styleIds: ['surreal', 'cinematic', 'realistic'],
    variables: [
      createRequiredVariable('location', '拍摄地点', '例如：巨大混凝土楼梯与开放广场'),
      createRequiredVariable('subject', '人物', '例如：撑着红伞的独行者'),
      createRequiredVariable('spatialElement', '空间元素', '例如：远处一组重复的方形窗口'),
      createRequiredVariable('scaleIllusion', '尺度错觉', '例如：人物仿佛正在把窗口像积木一样移动'),
      createRequiredVariable('lightingCondition', '光照', '例如：阴天均匀光与柔和方向性阴影'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-64',
    title: '生成式水墨纹理场',
    summary: '结合水墨渗化规律和生成式秩序构建抽象画面。',
    content: '围绕{{emotionalTheme}}创作生成式水墨纹理场，基础规则为{{growthRule}}。让墨色单元在宣纸上按照规则聚集、分叉和消散，局部形成{{focalPattern}}，同时保留渗化边缘、飞白、积墨和纸纤维的真实变化；使用{{inkPalette}}与大面积留白建立呼吸节奏，画面既有算法秩序又保留手工偶然性。不形成具体山水、人物或文字，不使用数字霓虹、规则重复贴图、边框或水印。',
    categoryId: 'experimental-abstract',
    medium: 'illustration',
    styleIds: ['abstract', 'oriental', 'minimal'],
    variables: [
      createRequiredVariable('emotionalTheme', '情绪主题', '例如：安静扩散的回声'),
      createRequiredVariable('growthRule', '生成规则', '例如：墨点沿不可见圆环向外分裂并逐渐变淡'),
      createRequiredVariable('focalPattern', '焦点形态', '例如：画面左下形成密集旋涡后向右上释放'),
      createRequiredVariable('inkPalette', '墨色', '例如：焦墨、淡墨与极少量石青'),
    ],
  }),
]
