import type { PromptTemplate } from '@/types'
import {
  createBuiltinPromptTemplate,
  createRequiredVariable,
} from './createPromptTemplate'

export const FOOD_STILL_LIFE_TEMPLATES: PromptTemplate[] = [
  createBuiltinPromptTemplate({
    id: 'tpl-7',
    title: '美食氛围特写',
    summary: '突出食物温度、质地和用餐氛围的写实摄影。',
    content: '拍摄{{dish}}的美食摄影特写，突出{{texture}}和刚刚完成烹饪的温度感。餐盘置于{{tableSetting}}中，加入少量与菜品相关的原料和餐具作为陪衬，但不遮挡主体；采用约50mm视角、略高机位和自然景深，焦点落在最具食欲的细节。使用{{lighting}}勾勒蒸汽、油脂或酱汁光泽，色彩真实温暖，餐具边缘与食物结构完整，不出现多余餐盘、漂浮配料、错误文字或水印。',
    categoryId: 'food-still-life',
    medium: 'photography',
    styleIds: ['realistic', 'natural', 'commercial'],
    variables: [
      createRequiredVariable('dish', '食物', '例如：刚出炉的菌菇披萨', '刚出炉的菌菇披萨'),
      createRequiredVariable('texture', '重点质感', '例如：酥脆饼边与融化奶酪', '酥脆饼边与融化奶酪'),
      createRequiredVariable('tableSetting', '桌面环境', '例如：深色木桌与亚麻餐巾', '深色木桌与亚麻餐巾'),
      createRequiredVariable('lighting', '光线', '例如：窗边侧逆光', '窗边侧逆光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-13',
    title: '饮品广告飞溅瞬间',
    summary: '用凝固的液体动态突出饮品口感与清爽卖点。',
    content: '为{{drink}}拍摄动态饮品广告，核心卖点是{{sellingPoint}}。容器垂直稳定地位于画面中心，周围出现受控的液体飞溅、{{garnish}}和细小水珠，动态方向围绕产品形成视觉引导，不遮挡主体轮廓；使用高速摄影质感和近距离标准视角，液体透明度与重力关系可信。{{backgroundColor}}背景配合明亮侧逆光，色彩清爽、材质锐利，不生成额外容器、错误商标、乱码、水印或不合理漂浮物。',
    categoryId: 'food-still-life',
    medium: 'photography',
    styleIds: ['commercial', 'realistic'],
    variables: [
      createRequiredVariable('drink', '饮品', '例如：透明玻璃瓶装柚子气泡水', '透明玻璃瓶装柚子气泡水'),
      createRequiredVariable('sellingPoint', '核心卖点', '例如：冰凉清爽与细密气泡', '冰凉清爽与细密气泡'),
      createRequiredVariable('garnish', '搭配元素', '例如：新鲜柚子片与薄荷叶', '新鲜柚子片与薄荷叶'),
      createRequiredVariable('backgroundColor', '背景色', '例如：明亮浅青色', '明亮浅青色'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-14',
    title: '古典静物油画',
    summary: '以古典绘画的光影和材质秩序组织器物与果实。',
    content: '创作一幅以{{objects}}为主体的古典静物油画，整体情绪为{{mood}}。物件置于{{setting}}上，通过高低错落和轻微重叠形成稳定三角构图，每件物品仍保持清晰轮廓和可信材质；单一侧上方光源照亮主要物件，背景逐渐沉入暗部，形成克制的明暗对比。使用层层罩染、细腻笔触和{{palette}}，保留画布纹理，不加入现代包装、摄影虚化、塑料质感、文字或水印。',
    categoryId: 'food-still-life',
    medium: 'illustration',
    styleIds: ['retro', 'natural'],
    variables: [
      createRequiredVariable('objects', '静物组合', '例如：石榴、银杯与白色亚麻布', '石榴、银杯与白色亚麻布'),
      createRequiredVariable('mood', '画面情绪', '例如：安静而丰盛', '安静而丰盛'),
      createRequiredVariable('setting', '承托环境', '例如：深色木桌', '深色木桌'),
      createRequiredVariable('palette', '色彩倾向', '例如：酒红、深褐与柔和金色', '酒红、深褐与柔和金色'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-35',
    title: '农贸市场餐桌纪实',
    summary: '记录食材来源、人物互动和真实用餐环境的生活画面。',
    content: '在{{marketSetting}}拍摄一张围绕{{foodSubject}}的纪实餐桌画面，记录{{humanMoment}}。采用35mm视角和观察者距离，让食物、双手与环境摊位共同构成前中后景，保留自然发生的轻微动作模糊和真实桌面痕迹；使用{{timeAndLight}}，色彩温暖但不过度调色，食材质地与人物动作可信。画面应像真实旅行报道，不摆拍奢华道具，不出现畸形手部、重复餐具、错误文字或水印。',
    categoryId: 'food-still-life',
    medium: 'photography',
    styleIds: ['cinematic', 'natural', 'realistic'],
    variables: [
      createRequiredVariable('marketSetting', '市场环境', '例如：海边小城的周末早市'),
      createRequiredVariable('foodSubject', '食物主体', '例如：刚烤好的香草扁面包'),
      createRequiredVariable('humanMoment', '人物瞬间', '例如：摊主把第一块递给等待的孩子'),
      createRequiredVariable('timeAndLight', '时间与光线', '例如：清晨穿过遮阳布的斑驳光线'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-36',
    title: '食材植物图鉴',
    summary: '用科学插画方式展示食材植株、切面和生长细节。',
    content: '为{{ingredient}}绘制一页植物学食材图鉴，展示完整植株、{{detailViews}}和成熟果实的剖切结构。所有视图遵循一致比例逻辑，叶脉、根系、表皮和内部组织准确清楚，使用{{illustrationMethod}}在暖白纸面上呈现细腻层次；以{{layout}}组织主视图与细节图，预留规则的文字标注位置但不生成具体小字。整体自然、克制并具有出版品质，不加入餐盘、摄影景深、装饰边框、错误器官或水印。',
    categoryId: 'food-still-life',
    medium: 'illustration',
    styleIds: ['natural', 'editorial', 'realistic'],
    variables: [
      createRequiredVariable('ingredient', '食材植物', '例如：紫色无花果'),
      createRequiredVariable('detailViews', '细节视图', '例如：花序、叶片正反面与果实切面'),
      createRequiredVariable('illustrationMethod', '绘制技法', '例如：水彩薄涂结合精细墨线'),
      createRequiredVariable('layout', '页面布局', '例如：中央主植株、四周环绕细节图'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-37',
    title: '微缩甜点工坊',
    summary: '把甜点结构转化为可探索的治愈系微缩场景。',
    content: '将{{dessert}}设计成一座可进入的微缩3D工坊，微型角色正在{{activity}}。利用甜点本身的夹层、糖霜、果粒和酥皮构成楼梯、工作台与空间分区，加入{{signatureDetail}}作为叙事焦点；采用等距视角、圆润建模和{{palette}}，材质既保留食物质感又具有微缩模型秩序。光线柔和温暖，角色比例统一，不生成恶心质地、悬浮结构、重复人物、文字或水印。',
    categoryId: 'food-still-life',
    medium: 'three-dimensional',
    styleIds: ['miniature', 'healing', 'surreal'],
    variables: [
      createRequiredVariable('dessert', '甜点', '例如：草莓千层蛋糕'),
      createRequiredVariable('activity', '微型活动', '例如：搬运新鲜草莓并修整奶油墙面'),
      createRequiredVariable('signatureDetail', '标志细节', '例如：由焦糖片搭成的透明升降梯'),
      createRequiredVariable('palette', '配色', '例如：奶油白、草莓红与烘焙金'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-38',
    title: '餐厅菜单概念版式',
    summary: '建立适合真实菜单内容替换的清晰信息层级。',
    content: '为{{restaurantType}}设计一页餐厅菜单概念版式，品牌气质为{{brandMood}}。使用{{gridStructure}}组织分类标题、菜名占位、简短描述占位和价格占位，阅读顺序清晰，并以{{graphicMotif}}作为少量识别元素；采用{{typography}}和不超过三种颜色，确保高对比度、充足行距与真实印刷边距。文字以整齐占位线表示而不是生成乱码，不使用难以阅读的装饰字体，不加入过多照片、促销贴纸或水印。',
    categoryId: 'food-still-life',
    medium: 'graphic-design',
    styleIds: ['typographic', 'editorial', 'minimal'],
    variables: [
      createRequiredVariable('restaurantType', '餐厅类型', '例如：季节性地中海小餐馆'),
      createRequiredVariable('brandMood', '品牌气质', '例如：松弛、质朴而精致'),
      createRequiredVariable('gridStructure', '网格结构', '例如：不对称双栏网格'),
      createRequiredVariable('graphicMotif', '图形母题', '例如：手绘橄榄枝与弧形餐盘轮廓'),
      createRequiredVariable('typography', '字体组合', '例如：人文衬线标题与简洁无衬线正文'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-39',
    title: '节日食品礼盒主视觉',
    summary: '面向节庆发布的礼盒陈列、纹样和传播主视觉。',
    content: '为{{giftBox}}设计节日礼盒传播主视觉，主题是{{festivalConcept}}。画面中央展示打开与闭合两种礼盒状态，包装结构、内部分格和食品数量清楚一致，周围以{{decorativeElements}}形成克制的节庆节奏；背景采用{{backgroundTreatment}}，结合精细纹样、烫金质感和清晰品牌留白。整体高级但不过度堆砌，文字区域使用规整占位，不出现错误食品、重复盒体、廉价高光、具体商标、乱码或水印。',
    categoryId: 'food-still-life',
    medium: 'graphic-design',
    styleIds: ['luxury', 'commercial', 'oriental'],
    variables: [
      createRequiredVariable('giftBox', '礼盒品类', '例如：东方茶点与花果茶礼盒'),
      createRequiredVariable('festivalConcept', '节日主题', '例如：月下相聚与四季丰收'),
      createRequiredVariable('decorativeElements', '装饰元素', '例如：桂花枝、圆月和细金线'),
      createRequiredVariable('backgroundTreatment', '背景处理', '例如：深靛蓝宣纸肌理与柔和光晕'),
    ],
  }),
]
