import type { PromptTemplate } from '@/types'
import {
  createBuiltinPromptTemplate,
  createRequiredVariable,
} from './createPromptTemplate'

export const GRAPHIC_COMMUNICATION_TEMPLATES: PromptTemplate[] = [
  createBuiltinPromptTemplate({
    id: 'tpl-8',
    title: '扁平信息插画',
    summary: '适合文章头图和传播页面的清晰扁平主题插画。',
    content: '围绕{{topic}}创作一幅扁平信息插画，用{{metaphor}}作为核心视觉隐喻。采用清晰的几何形状、有限层级和{{composition}}，主体轮廓简洁，辅助元素只用于解释主题；使用{{palette}}形成明确对比，并加入轻微纸张噪点避免画面过于机械。整体适合文章头图或数字传播页面，保留可裁切的安全留白，不生成具体品牌标识、乱码、装饰性小字或不必要的写实光影。',
    categoryId: 'graphic-communication',
    medium: 'illustration',
    styleIds: ['minimal', 'editorial'],
    variables: [
      createRequiredVariable('topic', '传播主题', '例如：团队远程协作', '团队远程协作'),
      createRequiredVariable('metaphor', '视觉隐喻', '例如：由不同模块连接成的桥梁', '由不同模块连接成的桥梁'),
      createRequiredVariable('composition', '构图', '例如：中心放射构图', '中心放射构图'),
      createRequiredVariable('palette', '配色', '例如：深蓝、橙色与米白', '深蓝、橙色与米白'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-20',
    title: '杂志封面视觉',
    summary: '为人物或主题内容建立可承载刊名和标题的编辑封面。',
    content: '为主题{{theme}}设计一张现代杂志封面，核心视觉为{{heroVisual}}。采用{{composition}}建立强主次关系，主体占据明确视觉中心，并在顶部刊名区、左右标题区和底部信息区保留干净空间；使用{{palette}}与克制的编辑摄影或拼贴质感，细节清晰，整体具有当代文化杂志气质。只生成版式占位关系，不生成具体可读文案、随机字母、现成品牌标志、水印或拥挤装饰。',
    categoryId: 'graphic-communication',
    medium: 'graphic-design',
    styleIds: ['editorial', 'typographic'],
    variables: [
      createRequiredVariable('theme', '封面主题', '例如：城市中的独立音乐文化', '城市中的独立音乐文化'),
      createRequiredVariable('heroVisual', '核心视觉', '例如：舞台灯光下的年轻乐队主唱', '舞台灯光下的年轻乐队主唱'),
      createRequiredVariable('composition', '版式结构', '例如：主体偏右的大面积留白构图', '主体偏右的大面积留白构图'),
      createRequiredVariable('palette', '配色', '例如：黑白基底与荧光绿色点缀', '黑白基底与荧光绿色点缀'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-21',
    title: '活动概念海报',
    summary: '以单一视觉概念和清晰信息层级构建传播海报。',
    content: '为{{event}}设计一张概念活动海报，视觉概念是{{visualConcept}}。采用{{layout}}，让核心图形、主标题占位区、日期占位区和辅助信息区形成清晰层级；使用{{palette}}与高对比图形语言，确保缩略图尺寸下仍能识别主题。画面可以保留少量印刷网点、套色偏移或纸张纹理，但不生成具体可读文案、随机乱码、现成商标、水印或无意义装饰元素。',
    categoryId: 'graphic-communication',
    medium: 'graphic-design',
    styleIds: ['typographic', 'editorial', 'retro'],
    variables: [
      createRequiredVariable('event', '活动主题', '例如：夏季独立电影展', '夏季独立电影展'),
      createRequiredVariable('visualConcept', '视觉概念', '例如：胶片被光束切割成城市剪影', '胶片被光束切割成城市剪影'),
      createRequiredVariable('layout', '版式', '例如：纵向非对称网格', '纵向非对称网格'),
      createRequiredVariable('palette', '配色', '例如：深红、奶油白与黑色', '深红、奶油白与黑色'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-55',
    title: '三维数据叙事主视觉',
    summary: '把抽象数据关系转化为易理解的三维视觉系统。',
    content: '围绕{{dataTopic}}创作三维数据叙事主视觉，用{{visualMetaphor}}表达核心关系。将数据层级映射为大小、位置、颜色和连接方式明确的3D几何系统，突出{{keyInsight}}，并为标题、摘要和图例预留规则区域；采用{{materialAndPalette}}、正交或轻透视视角和柔和环境光，确保缩小后仍能辨认。视觉应准确服务信息而非纯装饰，不伪造具体数字，不堆叠复杂粒子，不生成乱码、图表坐标或水印。',
    categoryId: 'graphic-communication',
    medium: 'three-dimensional',
    styleIds: ['abstract', 'minimal', 'editorial'],
    variables: [
      createRequiredVariable('dataTopic', '数据主题', '例如：城市公共交通中的换乘流动'),
      createRequiredVariable('visualMetaphor', '视觉隐喻', '例如：彼此连接的透明浮岛'),
      createRequiredVariable('keyInsight', '核心洞察', '例如：少数枢纽承担大部分跨区连接'),
      createRequiredVariable('materialAndPalette', '材质与配色', '例如：半透明玻璃、哑光蓝与高亮橙色'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-56',
    title: '摄影专题开篇版',
    summary: '为深度报道组织主照片、标题层级和阅读入口。',
    content: '为关于{{editorialTopic}}的深度报道设计摄影专题开篇版，主照片记录{{photoMoment}}。采用{{spreadLayout}}安排跨页照片、标题占位、导语占位和页码信息，人物或主要地标避开装订线与文字区域；照片使用{{photoStyle}}，保留真实环境细节和编辑出版所需的色调稳定性。整体阅读层级清晰，文字以规范占位块表示，不裁切关键面孔，不生成乱码、广告标志、过量装饰或水印。',
    categoryId: 'graphic-communication',
    medium: 'photography',
    styleIds: ['editorial', 'realistic', 'minimal'],
    variables: [
      createRequiredVariable('editorialTopic', '专题主题', '例如：沿海小镇如何适应不断变化的潮汐'),
      createRequiredVariable('photoMoment', '主照片瞬间', '例如：居民在涨潮前共同加固木制步道'),
      createRequiredVariable('spreadLayout', '跨页版式', '例如：左页满版照片、右页窄栏标题与导语'),
      createRequiredVariable('photoStyle', '摄影风格', '例如：自然阴天光线与克制纪实色彩'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-57',
    title: '社媒轮播信息卡',
    summary: '将复杂主题拆分为连续、易读且统一的多页信息卡。',
    content: '围绕{{communicationTopic}}设计一组五页社媒轮播信息卡，目标是让{{audience}}理解{{keyMessage}}。第一页建立主题钩子，第二至四页分别呈现问题、解释和行动建议，第五页总结并保留行动入口；使用{{visualSystem}}统一页码、标题、图标和信息层级，每页只保留一个核心观点。文字区域以规则占位表示，不生成乱码，确保移动端可读，不使用密集小字、过多颜色、无关照片、平台商标或水印。',
    categoryId: 'graphic-communication',
    medium: 'graphic-design',
    styleIds: ['typographic', 'commercial', 'minimal'],
    variables: [
      createRequiredVariable('communicationTopic', '传播主题', '例如：日常生活中的数据隐私'),
      createRequiredVariable('audience', '目标受众', '例如：刚开始独立使用网络服务的大学生'),
      createRequiredVariable('keyMessage', '核心信息', '例如：少量设置就能显著减少不必要的数据暴露'),
      createRequiredVariable('visualSystem', '视觉系统', '例如：粗体标题、圆角信息块与蓝紫渐变编号'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-58',
    title: '品牌理念隐喻插画',
    summary: '用一个清晰视觉隐喻解释抽象的品牌理念。',
    content: '为{{brandType}}创作品牌理念插画，核心理念是{{brandIdea}}，用{{visualMetaphor}}进行表达。画面设置一个明确主体和不超过三组辅助元素，通过尺度、方向和空间关系解释理念，而不是堆叠符号；采用{{illustrationStyle}}与{{palette}}，轮廓清楚，并为网页标题或品牌文案保留可裁切留白。整体亲和、独特且适合系列延展，不使用现成商标、陈词滥调握手图形、复杂小字、摄影光效或水印。',
    categoryId: 'graphic-communication',
    medium: 'illustration',
    styleIds: ['commercial', 'minimal', 'healing'],
    variables: [
      createRequiredVariable('brandType', '品牌类型', '例如：为小型团队提供工具的软件品牌'),
      createRequiredVariable('brandIdea', '品牌理念', '例如：让复杂协作变得清晰而轻松'),
      createRequiredVariable('visualMetaphor', '视觉隐喻', '例如：不同形状的船只共享一座灵活灯塔'),
      createRequiredVariable('illustrationStyle', '插画风格', '例如：柔和几何造型与轻微纸张纹理'),
      createRequiredVariable('palette', '配色', '例如：深海蓝、珊瑚橙与暖白'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-59',
    title: '丝网印文化活动海报',
    summary: '以有限色彩、套印质感和强轮廓传播文化活动。',
    content: '为{{culturalEvent}}设计丝网印刷风格海报，活动主题是{{eventTheme}}。以{{heroGraphic}}作为主图形，结合大字号标题占位和{{layoutRhythm}}建立强烈阅读节奏；限制使用{{inkColors}}，保留纸张纤维、网点、轻微套色偏差和真实印刷边缘，同时确保日期与地点区域清楚。画面具有手工传播感但不过度做旧，不模仿现成海报，不生成乱码、无关装饰、商业商标或水印。',
    categoryId: 'graphic-communication',
    medium: 'graphic-design',
    styleIds: ['retro', 'typographic', 'editorial'],
    variables: [
      createRequiredVariable('culturalEvent', '文化活动', '例如：城市独立书店夜间联展'),
      createRequiredVariable('eventTheme', '活动主题', '例如：阅读如何重新连接附近的人'),
      createRequiredVariable('heroGraphic', '主图形', '例如：由打开书页组成的发光街区'),
      createRequiredVariable('layoutRhythm', '版式节奏', '例如：倾斜主标题与底部密集信息带'),
      createRequiredVariable('inkColors', '印刷色', '例如：荧光橙、深蓝与纸张本色'),
    ],
  }),
]
