import type { PromptTemplate } from '@/types'
import {
  createBuiltinPromptTemplate,
  createRequiredVariable,
} from './createPromptTemplate'

export const LANDSCAPES_NATURE_TEMPLATES: PromptTemplate[] = [
  createBuiltinPromptTemplate({
    id: 'tpl-2',
    title: '国风水墨山水',
    summary: '以传统笔墨和留白关系组织具有诗意的山水画面。',
    content: '创作一幅描绘{{landscape}}的东方水墨山水，画面主题为{{mood}}。使用淡墨渲染远景、浓墨刻画近景，以{{composition}}组织山石、水面与云雾，保留大面积呼吸感和自然留白。纸面呈现细腻宣纸纤维、干湿笔触与墨色渗化，色彩以墨黑、灰白和少量{{accentColor}}点染，意境含蓄，不加入现代建筑、摄影光效、立体渲染或可读文字。',
    categoryId: 'landscapes-nature',
    medium: 'illustration',
    styleIds: ['oriental', 'natural', 'minimal'],
    variables: [
      createRequiredVariable('landscape', '山水主题', '例如：云雾中的高山湖泊', '云雾中的高山湖泊'),
      createRequiredVariable('mood', '画面意境', '例如：清寂悠远', '清寂悠远'),
      createRequiredVariable('composition', '构图方式', '例如：纵向深远构图', '纵向深远构图'),
      createRequiredVariable('accentColor', '点染色', '例如：低饱和朱砂红', '低饱和朱砂红'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-17',
    title: '电影感自然风景',
    summary: '通过尺度、天气与光线关系塑造具有叙事性的自然景观。',
    content: '拍摄{{landscape}}的电影感自然风景，画面表达{{mood}}。使用宽幅构图和{{viewpoint}}，前景安排具有触感的自然元素，中景建立主要地貌，远景延伸至天气与天空；{{weather}}在空间中形成清晰层次，{{lighting}}作为唯一可信主光。色彩低饱和且保留自然冷暖变化，细节丰富但不过度锐化，地貌尺度真实，不加入建筑、人物、奇幻天体、夸张HDR、文字或水印。',
    categoryId: 'landscapes-nature',
    medium: 'photography',
    styleIds: ['cinematic', 'natural', 'realistic'],
    variables: [
      createRequiredVariable('landscape', '自然景观', '例如：冰川融水形成的高山河谷', '冰川融水形成的高山河谷'),
      createRequiredVariable('mood', '情绪', '例如：辽阔而冷静', '辽阔而冷静'),
      createRequiredVariable('viewpoint', '观察位置', '例如：低位贴近河岸', '低位贴近河岸'),
      createRequiredVariable('weather', '天气', '例如：雨后低云正在散开', '雨后低云正在散开'),
      createRequiredVariable('lighting', '光线', '例如：云隙透出的傍晚侧光', '云隙透出的傍晚侧光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-18',
    title: '自然生态微距',
    summary: '观察微小生物与栖息环境之间真实细腻的生态关系。',
    content: '以微距摄影记录{{subject}}在{{habitat}}中的自然状态，正在{{behavior}}。镜头与主体保持平视或略低角度，焦点落在关键生理结构，浅景深只柔化远处背景，不牺牲主体轮廓；露水、叶片、土壤等环境材质符合真实尺度。使用{{lighting}}呈现细微纹理和半透明结构，色彩自然、克制，不摆拍成人工对称，不出现错误肢体、重复生物、巨大化道具、文字或水印。',
    categoryId: 'landscapes-nature',
    medium: 'photography',
    styleIds: ['natural', 'realistic'],
    variables: [
      createRequiredVariable('subject', '生态主体', '例如：停在苔藓上的蓝色蜻蜓', '停在苔藓上的蓝色蜻蜓'),
      createRequiredVariable('habitat', '栖息环境', '例如：清晨潮湿的溪边植物间', '清晨潮湿的溪边植物间'),
      createRequiredVariable('behavior', '自然行为', '例如：整理带有露水的翅膀', '整理带有露水的翅膀'),
      createRequiredVariable('lighting', '光线', '例如：树叶间透下的柔和逆光', '树叶间透下的柔和逆光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-45',
    title: '等高线地形模型',
    summary: '把真实地貌转化为层级清晰的三维地形展示。',
    content: '将{{landform}}制作成精细的3D等高线地形模型，重点展示{{geographicFeature}}。使用连续分层的等高线切片准确表达海拔变化、坡度和水系关系，以{{materialStyle}}区分山体、水面与植被区域，并在{{viewAngle}}下保持整体轮廓清楚；光线柔和，阴影帮助阅读高差，背景保持纯净。模型应具有科学可信度和展览质感，不随意增加建筑，不生成错误水流、悬浮地层、标注文字或水印。',
    categoryId: 'landscapes-nature',
    medium: 'three-dimensional',
    styleIds: ['miniature', 'natural', 'minimal'],
    variables: [
      createRequiredVariable('landform', '地貌区域', '例如：火山口与周围高原湖泊'),
      createRequiredVariable('geographicFeature', '地理重点', '例如：放射状沟谷和湖盆高差'),
      createRequiredVariable('materialStyle', '材质风格', '例如：叠层纸板、半透明树脂水面与细颗粒植被'),
      createRequiredVariable('viewAngle', '展示视角', '例如：略高的三分之四俯视'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-46',
    title: '国家公园导览海报',
    summary: '将代表性景观、路线层级和保护信息组织成旅行海报。',
    content: '为{{nationalPark}}设计导览海报，核心景观是{{landmark}}。以简化但可识别的地貌图形作为主体，使用{{layout}}组织公园名称占位、季节信息、三条路线和保护提示，路线通过清晰颜色与线型区分；采用{{visualStyle}}和{{palette}}，兼顾远距离吸引力与近距离阅读。所有文字使用规则占位而非乱码，地图关系必须合理，不堆叠过多图标，不加入商业促销、错误动物、商标或水印。',
    categoryId: 'landscapes-nature',
    medium: 'graphic-design',
    styleIds: ['typographic', 'editorial', 'natural'],
    variables: [
      createRequiredVariable('nationalPark', '国家公园', '例如：高山冰川与针叶林保护区'),
      createRequiredVariable('landmark', '核心景观', '例如：通向蓝色冰湖的峡谷步道'),
      createRequiredVariable('layout', '版式结构', '例如：上部景观主图、下部横向路线信息'),
      createRequiredVariable('visualStyle', '视觉风格', '例如：复古旅行版画结合现代信息图'),
      createRequiredVariable('palette', '配色', '例如：冰川蓝、森林绿与岩石米灰'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-47',
    title: '航拍河流地貌',
    summary: '从高空记录河道纹理、季节变化和地表尺度。',
    content: '航拍{{riverLandscape}}的自然地貌，重点呈现{{seasonalChange}}。采用垂直向下的无人机视角，将河道分汊、沙洲、植被边界和沉积纹理组织成清晰的自然图案，同时保留足够范围说明水系尺度；光线选择{{lightingCondition}}，色彩真实，水面反射受控，地表细节连续。画面应像高质量地理摄影，不加入建筑或人物焦点，不制造不合理河流方向、过饱和颜色、文字或水印。',
    categoryId: 'landscapes-nature',
    medium: 'photography',
    styleIds: ['realistic', 'natural', 'abstract'],
    variables: [
      createRequiredVariable('riverLandscape', '河流地貌', '例如：高原湿地中蜿蜒的辫状河'),
      createRequiredVariable('seasonalChange', '季节变化', '例如：秋季浅水露出的金色沙洲'),
      createRequiredVariable('lightingCondition', '光照条件', '例如：清晨低角度柔光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-48',
    title: '植物学标本图版',
    summary: '以出版级图版展示植物形态、生命周期和关键结构。',
    content: '为{{plantSpecies}}绘制出版级植物学标本图版，完整展示{{lifeStages}}。主视图呈现植株自然姿态，周围排列叶片正反面、花部结构、果实与种子的放大视图，各部分比例关系明确；使用{{renderingMethod}}刻画叶脉、表皮和色彩渐变，以{{pageComposition}}保留编号与说明占位。背景为干净暖白，科学准确且具有自然美感，不添加装饰花边、错误结构、摄影阴影、乱码或水印。',
    categoryId: 'landscapes-nature',
    medium: 'illustration',
    styleIds: ['natural', 'editorial', 'realistic'],
    variables: [
      createRequiredVariable('plantSpecies', '植物', '例如：高山蓝色龙胆'),
      createRequiredVariable('lifeStages', '生命周期', '例如：幼苗、盛花、结果与种子'),
      createRequiredVariable('renderingMethod', '表现技法', '例如：彩色铅笔细描结合透明水彩'),
      createRequiredVariable('pageComposition', '页面构图', '例如：左侧完整植株、右侧纵向细节序列'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-49',
    title: '极地极光全景',
    summary: '表现极地尺度、夜空层次和克制真实的极光色彩。',
    content: '拍摄{{polarLocation}}的极光自然全景，天空出现{{auroraShape}}。采用广角横幅构图，以{{foreground}}建立尺度和前景锚点，地平线保持水平，远处雪山或冰原层次清晰；使用长曝光但保留星点与极光帘幕结构，色彩以{{colorPalette}}为主，暗部仍有雪地纹理。画面壮阔、安静且符合真实夜间摄影，不出现巨大月亮、过量星轨、重复山峰、人造灯光、文字或水印。',
    categoryId: 'landscapes-nature',
    medium: 'photography',
    styleIds: ['cinematic', 'realistic', 'natural'],
    variables: [
      createRequiredVariable('polarLocation', '极地地点', '例如：冬季峡湾旁的黑沙海岸'),
      createRequiredVariable('auroraShape', '极光形态', '例如：从山谷升起的弧形光幕'),
      createRequiredVariable('foreground', '前景', '例如：覆盖薄雪的深色岩石与潮汐水面'),
      createRequiredVariable('colorPalette', '色彩', '例如：低饱和翡翠绿、深蓝与少量紫色'),
    ],
  }),
]
