import type { PromptTemplate } from '@/types'
import {
  createBuiltinPromptTemplate,
  createRequiredVariable,
} from './createPromptTemplate'

export const NARRATIVE_WORLDBUILDING_TEMPLATES: PromptTemplate[] = [
  createBuiltinPromptTemplate({
    id: 'tpl-4',
    title: '温暖动画场景',
    summary: '适合日常叙事、温柔冒险和治愈氛围的手绘场景。',
    content: '绘制{{character}}置身于{{scene}}的温暖手绘动画场景，正在{{action}}。采用清晰的前景、中景和远景层次，让人物动作与环境细节共同讲述一个安静的日常故事；画面以{{timeOfDay}}的柔和自然光照明，云朵、植物和建筑具有轻微夸张但保持可信结构。使用水彩与不透明颜料结合的手绘质感，色彩温暖柔和，边缘自然，不使用真实摄影景深、塑料3D材质、品牌标识或可读文字。',
    categoryId: 'narrative-worldbuilding',
    medium: 'illustration',
    styleIds: ['healing', 'natural'],
    variables: [
      createRequiredVariable('character', '角色', '例如：背着画板的少年', '背着画板的少年'),
      createRequiredVariable('scene', '场景', '例如：山坡上的旧车站', '山坡上的旧车站'),
      createRequiredVariable('action', '正在发生的事', '例如：等待最后一班列车', '等待最后一班列车'),
      createRequiredVariable('timeOfDay', '时间与光线', '例如：夏日下午', '夏日下午'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-5',
    title: '赛博朋克城市叙事',
    summary: '构建具有明确人物行动和空间层次的未来城市镜头。',
    content: '创作发生在{{location}}的赛博朋克电影场面，主角{{character}}正在{{event}}。使用24mm广角和略低机位呈现密集城市纵深，前景包含雨水、蒸汽与经过的行人，中景聚焦主角，远景展示高层建筑和交通系统。{{lightingColor}}的霓虹光在湿润路面形成受控反射，暗部仍保留材质细节；画面写实、紧张且有明确视觉焦点，科技元素服务于叙事，不堆叠无意义标牌，不生成乱码、水印或重复人物。',
    categoryId: 'narrative-worldbuilding',
    medium: 'photography',
    styleIds: ['science-fiction', 'cinematic', 'realistic'],
    variables: [
      createRequiredVariable('location', '未来地点', '例如：多层轨道下的商业街', '多层轨道下的商业街'),
      createRequiredVariable('character', '主角', '例如：穿防雨外套的快递员', '穿防雨外套的快递员'),
      createRequiredVariable('event', '剧情动作', '例如：在人群中寻找失联终端', '在人群中寻找失联终端'),
      createRequiredVariable('lightingColor', '霓虹主色', '例如：青蓝与琥珀色', '青蓝与琥珀色'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-19',
    title: '奇幻遗迹探索',
    summary: '以人物尺度和环境线索建立可信的奇幻冒险世界。',
    content: '描绘{{explorer}}进入{{ruins}}的奇幻叙事场景，正在{{discovery}}。使用宽幅远景和略高观察位置，让角色在宏大空间中保持清晰尺度；遗迹结构遵循一致的建造逻辑，前景散落与文明相关的线索，中远景通过雾气和光线延伸深度。{{magicalElement}}作为唯一超自然视觉核心，光效影响周围材质和人物，不堆叠无关特效；整体色彩神秘克制，不出现现代物件、重复人物、乱码或水印。',
    categoryId: 'narrative-worldbuilding',
    medium: 'illustration',
    styleIds: ['fantasy', 'cinematic'],
    variables: [
      createRequiredVariable('explorer', '探索者', '例如：携带旧地图的年轻学者', '携带旧地图的年轻学者'),
      createRequiredVariable('ruins', '遗迹', '例如：被森林吞没的环形石城', '被森林吞没的环形石城'),
      createRequiredVariable('discovery', '发现事件', '例如：打开通向地下星图室的入口', '打开通向地下星图室的入口'),
      createRequiredVariable('magicalElement', '魔法核心', '例如：悬浮在入口上方的蓝色符文', '悬浮在入口上方的蓝色符文'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-50',
    title: '科幻游戏关卡关键帧',
    summary: '明确展示关卡目标、空间路径和电影化冲突。',
    content: '为科幻游戏关卡{{levelLocation}}创作3D关键帧，玩家目标是{{mission}}。使用{{cameraPosition}}展示可行走路径、关键入口、掩体与远处目标，前景安排{{storyEvent}}制造即时冲突；建筑、设备和交通系统遵循统一技术逻辑，使用电影级体积光、物理材质与受控环境特效。画面既有叙事张力又能读出关卡结构，不堆叠无意义机械，不出现封闭路线、重复角色、界面文字或水印。',
    categoryId: 'narrative-worldbuilding',
    medium: 'three-dimensional',
    styleIds: ['science-fiction', 'cinematic', 'realistic'],
    variables: [
      createRequiredVariable('levelLocation', '关卡地点', '例如：木星轨道上的废弃燃料港'),
      createRequiredVariable('mission', '任务目标', '例如：穿过装卸区重启逃生电梯'),
      createRequiredVariable('cameraPosition', '镜头位置', '例如：低位广角、从损坏货柜后向外观察'),
      createRequiredVariable('storyEvent', '剧情事件', '例如：远处闸门突然开启并涌出冷雾'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-51',
    title: '奇幻世界旅行海报',
    summary: '用目的地景观和旅行信息构建可信的幻想世界宣传物。',
    content: '为奇幻目的地{{destination}}设计旅行海报，宣传主题是{{travelPromise}}。以{{landmark}}作为中央主图，加入少量当地交通工具、居民剪影和环境细节建立尺度；使用{{posterStyle}}、明确的标题占位和三层信息网格，配色来自目的地自然环境并保留票务信息区域。画面要像该世界真实发行的旅行宣传物，文字使用规整占位，不拼贴现成IP，不出现混乱建筑风格、乱码、商标或水印。',
    categoryId: 'narrative-worldbuilding',
    medium: 'graphic-design',
    styleIds: ['typographic', 'fantasy', 'retro'],
    variables: [
      createRequiredVariable('destination', '奇幻目的地', '例如：漂浮鲸群迁徙经过的云上港城'),
      createRequiredVariable('travelPromise', '旅行主题', '例如：在天空尽头等待一年一次的潮汐'),
      createRequiredVariable('landmark', '标志景观', '例如：连接三座浮岛的白色风帆桥'),
      createRequiredVariable('posterStyle', '海报风格', '例如：二十世纪旅行石版画与现代网格结合'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-52',
    title: '历史冒险场面',
    summary: '以可信时代细节和明确行动构建历史叙事插画。',
    content: '绘制发生在{{historicalSetting}}的历史冒险场面，主角{{protagonist}}正在{{action}}。采用宽幅电影构图，通过前景障碍、中景人物和远景地标建立清晰空间方向，服装、工具、建筑和交通方式符合{{periodDetails}}；使用{{lighting}}强化时间压力与行动焦点，笔触具有传统叙事插画质感。场景紧张但不杂乱，不混入错误时代物品，不生成多余肢体、重复人物、现代标志、文字或水印。',
    categoryId: 'narrative-worldbuilding',
    medium: 'illustration',
    styleIds: ['retro', 'cinematic', 'realistic'],
    variables: [
      createRequiredVariable('historicalSetting', '历史环境', '例如：大航海时代暴雨前的山城港口'),
      createRequiredVariable('protagonist', '主角', '例如：携带密封航海图的年轻信使'),
      createRequiredVariable('action', '关键行动', '例如：穿过拥挤码头赶向即将离港的船'),
      createRequiredVariable('periodDetails', '时代细节', '例如：十六世纪末的服饰、帆船与石砌仓库'),
      createRequiredVariable('lighting', '光线', '例如：乌云裂隙中的最后一道金色侧光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-53',
    title: '纪录片式人物瞬间',
    summary: '通过人物行动和真实环境讲述一个未被摆拍的故事。',
    content: '在{{realWorldSetting}}记录{{subject}}的纪录片式人物瞬间，人物正在{{activity}}。采用{{framing}}和自然观察距离，让动作、工具、工作环境与旁观者共同提供叙事信息，保留环境中真实的凌乱和时间痕迹；使用现场{{availableLight}}，肤色、材质与明暗过渡自然，不追求广告式完美。照片应尊重人物并避免猎奇，不摆拍直视镜头，不出现畸形手部、重复物件、夸张滤镜、文字或水印。',
    categoryId: 'narrative-worldbuilding',
    medium: 'photography',
    styleIds: ['realistic', 'cinematic', 'natural'],
    variables: [
      createRequiredVariable('realWorldSetting', '真实场景', '例如：黎明前开始工作的老火车维修库'),
      createRequiredVariable('subject', '人物', '例如：检查蒸汽管线的资深维修工'),
      createRequiredVariable('activity', '正在发生的事', '例如：与年轻学徒确认一处细小泄漏'),
      createRequiredVariable('framing', '构图', '例如：包含环境的中景侧面构图'),
      createRequiredVariable('availableLight', '现场光线', '例如：高窗冷光与工作灯暖光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-54',
    title: '梦境转场拼贴',
    summary: '把两个场景通过视觉隐喻无缝连接成叙事转场。',
    content: '创作一幅从{{firstScene}}过渡到{{secondScene}}的梦境拼贴，转场隐喻是{{transitionMetaphor}}。让两个空间共享一条连续的视觉动线，通过尺度变化、材质替换和{{connectingElement}}逐步完成转换，而不是简单左右拼接；采用{{palette}}、手工剪贴边缘和细腻绘画层，保留一个清晰的人物或物体作为观看锚点。画面超现实但关系可理解，不堆叠随机元素，不出现重复主体、乱码、现成照片边框或水印。',
    categoryId: 'narrative-worldbuilding',
    medium: 'illustration',
    styleIds: ['surreal', 'editorial', 'cinematic'],
    variables: [
      createRequiredVariable('firstScene', '起始场景', '例如：深夜仍亮着灯的学校走廊'),
      createRequiredVariable('secondScene', '目标场景', '例如：漂浮在云海中的长途列车站'),
      createRequiredVariable('transitionMetaphor', '转场隐喻', '例如：记忆像潮水淹没熟悉空间'),
      createRequiredVariable('connectingElement', '连接元素', '例如：不断延伸并变成铁轨的地面反光'),
      createRequiredVariable('palette', '配色', '例如：墨蓝、月光白与低饱和橙色'),
    ],
  }),
]
