import type { PromptTemplate } from '@/types'
import {
  createBuiltinPromptTemplate,
  createRequiredVariable,
} from './createPromptTemplate'

// Foundational people and character templates.
export const PEOPLE_CHARACTER_TEMPLATES: PromptTemplate[] = [
  createBuiltinPromptTemplate({
    id: 'tpl-1',
    title: '电影感环境人像',
    summary: '让人物与真实环境共同承担叙事的电影感肖像。',
    content: '在{{scene}}中创作{{person}}的电影感环境人像。人物呈现{{action}}，主体与环境之间保留清晰的叙事关系；采用35mm环境人像视角和{{framing}}，自然透视、浅景深，人物五官与肢体结构准确。使用{{lighting}}作为主光，背景保留明暗层次，整体采用低饱和电影调色和细腻胶片颗粒，画面真实克制，不添加多余文字、水印或无关元素。',
    categoryId: 'people-characters',
    medium: 'photography',
    styleIds: ['cinematic', 'realistic'],
    variables: [
      createRequiredVariable('scene', '拍摄场景', '例如：雨后的旧城区街口', '雨后的旧城区街口'),
      createRequiredVariable('person', '人物设定', '例如：短发女性建筑师', '短发女性建筑师'),
      createRequiredVariable('action', '动作与情绪', '例如：停步回望，神情平静', '停步回望，神情平静'),
      createRequiredVariable('framing', '景别', '例如：半身构图', '半身构图'),
      createRequiredVariable('lighting', '光线', '例如：黄昏侧逆光', '黄昏侧逆光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-9',
    title: '时尚杂志棚拍',
    summary: '突出服装廓形、人物姿态和编辑气质的棚拍大片。',
    content: '为{{model}}拍摄一组时尚杂志棚拍主图，重点展示{{outfit}}的廓形与材质。人物采用{{pose}}，神态克制自信，身体结构和服装细节准确；使用中长焦人像视角与{{framing}}，背景为简洁的灰阶影棚空间。大面积柔光作为主光，侧后方窄光勾勒轮廓，整体低饱和、锐利而不过度磨皮，保留真实皮肤纹理和织物细节，不出现多余肢体、错误配饰、文字或水印。',
    categoryId: 'people-characters',
    medium: 'photography',
    styleIds: ['editorial', 'commercial', 'realistic'],
    variables: [
      createRequiredVariable('model', '人物设定', '例如：银色短发的青年模特', '银色短发的青年模特'),
      createRequiredVariable('outfit', '服装造型', '例如：结构感黑色长外套', '结构感黑色长外套'),
      createRequiredVariable('pose', '姿态', '例如：侧身站立并直视镜头', '侧身站立并直视镜头'),
      createRequiredVariable('framing', '景别', '例如：四分之三身', '四分之三身'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-10',
    title: '角色设定展示板',
    summary: '在一张画面中明确呈现原创角色的造型、细节和配色。',
    content: '为原创角色{{character}}制作一张专业角色设定展示板，角色身份是{{role}}。画面包含正面全身主视图、侧面轮廓和两处关键细节放大，服装与装备围绕{{designMotif}}形成统一设计语言；使用{{palette}}，结构线条清楚，材质区分明确，人体比例在各视图中保持一致。采用干净的中性背景和有秩序的编辑排版，不加入大段说明文字、现成IP标识、重复肢体或互相矛盾的服装细节。',
    categoryId: 'people-characters',
    medium: 'illustration',
    styleIds: ['fantasy', 'editorial'],
    variables: [
      createRequiredVariable('character', '角色名称或外形', '例如：鹿角森林信使', '鹿角森林信使'),
      createRequiredVariable('role', '角色身份', '例如：负责传递季节消息的旅行者', '负责传递季节消息的旅行者'),
      createRequiredVariable('designMotif', '设计母题', '例如：树叶、邮袋与铜制铃铛', '树叶、邮袋与铜制铃铛'),
      createRequiredVariable('palette', '角色配色', '例如：苔绿、皮革棕与铜金', '苔绿、皮革棕与铜金'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-25',
    title: '专业职业头像',
    summary: '为个人主页、团队介绍和专业社交平台制作可信头像。',
    content: '为{{person}}拍摄专业职业头像，传达{{professionalQuality}}。人物穿着{{wardrobe}}，采用自然放松的肩部姿态和稳定目光，保留真实面部结构、皮肤纹理与发丝细节；使用85mm人像视角、胸像构图和眼平机位，以柔和主光、轻微轮廓光和{{background}}形成清晰分离。整体克制可信，适合个人主页与团队介绍，不夸张磨皮，不出现多余配饰、文字、水印或变形五官。',
    categoryId: 'people-characters',
    medium: 'photography',
    styleIds: ['realistic', 'commercial', 'minimal'],
    variables: [
      createRequiredVariable('person', '人物设定', '例如：三十岁的女性产品设计师'),
      createRequiredVariable('professionalQuality', '职业气质', '例如：可靠、敏锐且平易近人'),
      createRequiredVariable('wardrobe', '服装', '例如：剪裁简洁的深蓝西装'),
      createRequiredVariable('background', '背景', '例如：低饱和暖灰渐变背景'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-26',
    title: '风格化3D角色转面',
    summary: '用统一比例和材质呈现可用于建模沟通的角色转面。',
    content: '为{{character}}制作风格化3D角色转面展示，角色身份是{{role}}。在同一画面中并列呈现正面、侧面和背面全身视图，各视图保持完全一致的身高、比例、服装结构与装备位置；造型围绕{{designMotif}}展开，使用{{materialStyle}}材质和中性工作室灯光，轮廓清楚、拓扑感合理。背景纯净并保留适当间距，不添加透视夸张、动作姿态、重复肢体、说明文字或互相矛盾的细节。',
    categoryId: 'people-characters',
    medium: 'three-dimensional',
    styleIds: ['fantasy', 'editorial', 'minimal'],
    variables: [
      createRequiredVariable('character', '角色外形', '例如：戴护目镜的沙漠机械师'),
      createRequiredVariable('role', '角色身份', '例如：维护移动城市能源核心的工程师'),
      createRequiredVariable('designMotif', '设计母题', '例如：风蚀金属、绳结与太阳纹样'),
      createRequiredVariable('materialStyle', '材质风格', '例如：哑光粘土与少量磨损金属'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-27',
    title: '游戏角色主视觉',
    summary: '突出角色能力、装备和世界观氛围的三维宣传画面。',
    content: '为游戏角色{{hero}}创作高完成度3D主视觉，角色正在{{action}}，核心能力表现为{{ability}}。采用略低机位的全身动态构图，让武器、服装轮廓和动作方向形成清晰视觉焦点；背景以{{environment}}提供世界观线索，但控制景深与细节密度。使用电影级体积光、物理可信材质和受控粒子效果，人物面部与手部结构准确，不堆叠无意义特效，不出现多余肢体、界面文字、标志或水印。',
    categoryId: 'people-characters',
    medium: 'three-dimensional',
    styleIds: ['cinematic', 'science-fiction', 'realistic'],
    variables: [
      createRequiredVariable('hero', '英雄角色', '例如：携带折叠长枪的轨道巡守者'),
      createRequiredVariable('action', '角色动作', '例如：落地后转身迎战'),
      createRequiredVariable('ability', '核心能力', '例如：操纵环形重力场'),
      createRequiredVariable('environment', '背景环境', '例如：受损的月面交通枢纽'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-28',
    title: '个人品牌肖像海报',
    summary: '把人物肖像、姓名层级和专业定位组织成品牌海报。',
    content: '为{{person}}设计个人品牌肖像海报，核心定位是{{positioning}}。以一张边缘清晰、表情自然的半身肖像作为主要图形，使用{{layout}}组织人物、姓名占位和简短定位信息；字体采用{{typographyStyle}}，建立明确字号层级和对齐关系，配色限制在三种以内并保留充足安全留白。整体具有编辑感且便于社交媒体裁切，不生成具体乱码，用抽象文字块表示待替换内容，不添加多余装饰、品牌标志或水印。',
    categoryId: 'people-characters',
    medium: 'graphic-design',
    styleIds: ['typographic', 'editorial', 'minimal'],
    variables: [
      createRequiredVariable('person', '人物设定', '例如：独立字体设计师'),
      createRequiredVariable('positioning', '个人定位', '例如：连接传统书写与数字媒介'),
      createRequiredVariable('layout', '版式结构', '例如：人物右置、左侧纵向文字层级'),
      createRequiredVariable('typographyStyle', '字体气质', '例如：现代无衬线与细窄衬线混排'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-29',
    title: '超现实时尚拼贴',
    summary: '通过手绘、剪贴和尺度错位塑造实验人物形象。',
    content: '围绕{{model}}创作超现实时尚拼贴肖像，视觉概念为{{concept}}。将人物清晰轮廓与{{collageElements}}进行有控制的切割、遮挡和尺度错位，保留眼神、服装廓形与主要姿态的可读性；使用{{palette}}和纸张撕边、丝网印刷网点、蜡笔笔触等混合媒介质感。构图大胆但保持单一焦点，不模仿现成杂志或艺术家，不生成多余面孔、畸形手部、可读文字、商标或水印。',
    categoryId: 'people-characters',
    medium: 'illustration',
    styleIds: ['surreal', 'editorial', 'retro'],
    variables: [
      createRequiredVariable('model', '人物造型', '例如：穿银色褶皱礼服的短发模特'),
      createRequiredVariable('concept', '视觉概念', '例如：记忆在城市中开花'),
      createRequiredVariable('collageElements', '拼贴元素', '例如：巨型花瓣、旧地图与金属切片'),
      createRequiredVariable('palette', '配色', '例如：银灰、深红与褪色青绿'),
    ],
  }),
]
