import type { PromptTemplate } from '@/types'
import {
  createBuiltinPromptTemplate,
  createRequiredVariable,
} from './createPromptTemplate'

// Photography-focused portrait templates.
export const PORTRAIT_PHOTOGRAPHY_TEMPLATES: PromptTemplate[] = [
  createBuiltinPromptTemplate({
    id: 'tpl-65',
    title: '清透日系生活写真',
    summary: '以自然光、低对比色彩和生活化动作呈现轻盈日常感。',
    content: '为{{person}}拍摄清透日系生活写真，场景位于{{location}}，人物正在{{activity}}。采用50mm标准视角和自然观察距离，以窗边或树荫下的柔和散射光保留通透肤色、发丝和衣料细节；使用{{palette}}与轻微胶片颗粒，构图包含适量环境和偶然感，不要求人物持续直视镜头。整体松弛、安静且像真实生活片段，不进行过度磨皮，不制造虚假逆光，不出现畸形手部、重复人物、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['healing', 'natural', 'realistic'],
    variables: [
      createRequiredVariable('person', '人物设定', '例如：穿浅蓝衬衫的短发女生'),
      createRequiredVariable('location', '生活场景', '例如：安静的旧书店窗边'),
      createRequiredVariable('activity', '自然动作', '例如：翻看一本带手写批注的旧书'),
      createRequiredVariable('palette', '色彩倾向', '例如：奶油白、浅木色与雾蓝'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-66',
    title: '海边逆光氛围写真',
    summary: '利用海风、落日轮廓光和自然动作塑造开阔情绪。',
    content: '在{{coastline}}为{{person}}拍摄海边逆光写真，人物呈现{{moodAndAction}}。采用中远景与近景交替的视觉感受，地平线保持稳定，海风自然带动头发和{{wardrobe}}；使用日落前的低角度逆光勾勒轮廓，让面部仍保留柔和补光和真实肤色，海面高光受控。画面开阔、温柔并具有电影余韵，不让人物变成纯黑剪影，不夸张天空颜色，不出现多余肢体、凌乱游客、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['cinematic', 'natural', 'healing'],
    variables: [
      createRequiredVariable('coastline', '海边环境', '例如：退潮后的宽阔浅滩'),
      createRequiredVariable('person', '人物设定', '例如：长卷发的年轻女性'),
      createRequiredVariable('moodAndAction', '动作与情绪', '例如：提着鞋缓慢走过水面，神情放松'),
      createRequiredVariable('wardrobe', '服装', '例如：随风摆动的米白亚麻长裙'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-67',
    title: '城市霓虹夜景写真',
    summary: '在真实夜间街道中平衡人物肤色、霓虹色温和城市纵深。',
    content: '在{{nightLocation}}为{{person}}拍摄城市霓虹夜景写真，人物正在{{action}}。使用35mm环境人像视角，将前景反光、中景人物和远处城市灯光组成明确纵深；以{{neonPalette}}作为环境色，同时用柔和中性补光保持面部结构与肤色自然，湿润路面产生受控反射。画面时髦、克制且具有夜行叙事，不堆叠赛博元素，不让背景招牌成为乱码焦点，不出现过度锐化、重复行人、畸形手部或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['cinematic', 'science-fiction', 'realistic'],
    variables: [
      createRequiredVariable('nightLocation', '夜景地点', '例如：雨后高架桥下的便利店街口'),
      createRequiredVariable('person', '人物造型', '例如：穿黑色短夹克的银灰短发青年'),
      createRequiredVariable('action', '人物动作', '例如：撑透明雨伞侧身等待绿灯'),
      createRequiredVariable('neonPalette', '霓虹配色', '例如：青蓝环境光与少量琥珀色'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-68',
    title: '复古胶片街巷写真',
    summary: '通过老街环境、暖色胶片和随性抓拍还原年代气息。',
    content: '在{{oldStreet}}为{{person}}拍摄复古胶片街巷写真，人物穿着{{wardrobe}}并进行{{activity}}。采用35mm胶片相机般的视角、轻微颗粒和不过度完美的抓拍构图，保留旧墙、店铺门窗和街道生活细节；使用{{filmPalette}}，高光柔和、阴影略带色偏，但面部和服装颜色仍可信。画面应像真实年代旅行照片，不添加虚假日期、廉价漏光、现代广告焦点、重复人物、错误文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['retro', 'natural', 'editorial'],
    variables: [
      createRequiredVariable('oldStreet', '街巷环境', '例如：午后光线中的南方骑楼老街'),
      createRequiredVariable('person', '人物设定', '例如：自然卷发的年轻插画师'),
      createRequiredVariable('wardrobe', '复古服装', '例如：砖红针织衫与高腰深色长裤'),
      createRequiredVariable('activity', '人物动作', '例如：拿着纸袋从街角小店走出'),
      createRequiredVariable('filmPalette', '胶片色调', '例如：暖黄高光、青灰阴影与低饱和红色'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-69',
    title: '黑白情绪肖像写真',
    summary: '以精确明暗、细微表情和纯净背景表现人物内在状态。',
    content: '为{{person}}拍摄黑白情绪肖像写真，核心情绪是{{emotion}}。采用{{framing}}和略偏离正面的观察角度，让眼神、呼吸和细微面部动作成为视觉重点；使用{{lighting}}塑造从高光到深影的完整灰阶，保留皮肤、发丝和服装材质，不进行塑料化磨皮。背景简洁且不抢夺注意力，画面克制、诚实并具有展览级肖像质感，不使用纯黑死影、夸张泪痕、多余饰品、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['editorial', 'minimal', 'realistic'],
    variables: [
      createRequiredVariable('person', '人物设定', '例如：留有细微岁月痕迹的中年演员'),
      createRequiredVariable('emotion', '核心情绪', '例如：平静中带有短暂犹疑'),
      createRequiredVariable('framing', '景别', '例如：紧凑肩部特写'),
      createRequiredVariable('lighting', '黑白布光', '例如：单侧大窗柔光与轻微负补光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-70',
    title: '森系自然写真',
    summary: '让人物融入林地光影、植物层次和安静自然气息。',
    content: '在{{forestSetting}}为{{person}}拍摄森系自然写真，人物正在{{gentleAction}}。采用50mm视角，在前景叶片、中景人物和远景林木之间建立柔和层次，使用穿过树冠的散射光与少量光斑，保持肤色自然并清楚呈现{{wardrobe}}的织物质感；整体采用{{palette}}和低饱和调色。人物与环境关系亲近但主体仍明确，不制造过量仙气、漂浮花瓣、塑料皮肤、错误植物、畸形手部或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['natural', 'healing', 'realistic'],
    variables: [
      createRequiredVariable('forestSetting', '森林场景', '例如：雨后长满蕨类的山谷林地'),
      createRequiredVariable('person', '人物设定', '例如：扎低马尾的年轻陶艺师'),
      createRequiredVariable('gentleAction', '自然动作', '例如：轻触叶面上的水珠并低头观察'),
      createRequiredVariable('wardrobe', '服装', '例如：宽松燕麦色针织衫与深绿长裙'),
      createRequiredVariable('palette', '配色', '例如：苔绿、木棕与柔和米白'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-71',
    title: '居家晨光生活写真',
    summary: '记录清晨室内的日常动作、柔软质地和亲密生活感。',
    content: '在{{homeSpace}}为{{person}}拍摄居家晨光生活写真，记录人物{{morningActivity}}的自然瞬间。使用35mm或50mm视角，让窗框、家具和生活物件形成稳定环境关系，以{{morningLight}}照亮面部和手部，保留床品、木材与衣物的柔软纹理；服装为{{wardrobe}}，色彩温暖但不过度泛黄。画面应像真实居家记录，不刻意摆拍性感姿势，不制造杂乱道具，不出现过曝窗户、畸形肢体、重复物件、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['healing', 'natural', 'realistic'],
    variables: [
      createRequiredVariable('homeSpace', '居家空间', '例如：带木质百叶窗的小公寓厨房'),
      createRequiredVariable('person', '人物设定', '例如：刚起床、短发微乱的女生'),
      createRequiredVariable('morningActivity', '清晨活动', '例如：一边煮咖啡一边给窗边植物浇水'),
      createRequiredVariable('morningLight', '晨间光线', '例如：透过薄帘的低角度暖白阳光'),
      createRequiredVariable('wardrobe', '服装', '例如：宽松白衬衫与浅灰棉质长裤'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-72',
    title: '旅行纪实街拍写真',
    summary: '以旅行地真实环境和移动中的人物构成轻纪实肖像。',
    content: '在{{travelDestination}}为{{traveler}}拍摄旅行纪实街拍写真，人物正在{{travelMoment}}。采用35mm环境视角和步行者高度，保留当地建筑、交通、居民活动与天气细节，同时通过色彩或光线让主体自然突出；使用{{weatherAndLight}}和真实快门感，画面包含轻微运动与偶然构图。旅行感来自人与地点的互动，而不是景点摆拍，不清空当地居民，不制造假笑，不出现错误地标、重复行人、乱码招牌或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['editorial', 'natural', 'realistic'],
    variables: [
      createRequiredVariable('travelDestination', '旅行地点', '例如：清晨刚开始营业的山城集市'),
      createRequiredVariable('traveler', '旅行人物', '例如：背帆布相机包的独行青年'),
      createRequiredVariable('travelMoment', '旅行瞬间', '例如：停下来向水果摊主询问路线'),
      createRequiredVariable('weatherAndLight', '天气与光线', '例如：薄雾散开时的柔和侧光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-73',
    title: '雨天电影叙事写真',
    summary: '通过雨幕、反射和人物行动构建具有前后情节的电影画面。',
    content: '在{{rainyScene}}为{{person}}拍摄雨天电影叙事写真，画面发生的事件是{{storyMoment}}。采用{{cameraLanguage}}，以前景雨滴或玻璃反射、中景人物和远景环境建立空间层次；使用{{lightingPalette}}在湿润地面形成克制反光，人物衣物呈现真实受潮质感，面部仍清楚可辨。画面应暗示事件发生前后而非单纯淋雨摆拍，不堆叠霓虹，不制造倾盆水墙，不出现透明雨伞畸变、重复人物、乱码或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['cinematic', 'realistic', 'editorial'],
    variables: [
      createRequiredVariable('rainyScene', '雨天场景', '例如：末班车离开后的郊区公交站'),
      createRequiredVariable('person', '人物设定', '例如：抱着一束被雨打湿鲜花的年轻男子'),
      createRequiredVariable('storyMoment', '叙事瞬间', '例如：看见远处有人撑伞向自己跑来'),
      createRequiredVariable('cameraLanguage', '镜头语言', '例如：50mm中景、隔着带雨滴的玻璃观察'),
      createRequiredVariable('lightingPalette', '光线配色', '例如：冷灰环境光与站牌暖黄顶光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-74',
    title: '春日花园清新人像写真',
    summary: '在真实花园层次中表现春季色彩和轻快人物状态。',
    content: '在{{garden}}为{{person}}拍摄春日花园清新人像写真，人物进行{{action}}。采用中长焦压缩适量花木层次，以前景少量虚化花枝框住主体，但不遮挡面部和手部；使用{{springLight}}保持明亮肤色与花瓣细节，服装{{wardrobe}}和环境形成柔和色彩呼应。画面清新但不过度粉白，不生成漫天花瓣或虚假花海，不把花朵贴在人脸上，不出现畸形手指、重复植物、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['natural', 'healing', 'realistic'],
    variables: [
      createRequiredVariable('garden', '花园场景', '例如：盛开白色木绣球的旧宅庭院'),
      createRequiredVariable('person', '人物设定', '例如：自然长发的年轻女性'),
      createRequiredVariable('action', '人物动作', '例如：侧身修剪一枝过长的花枝'),
      createRequiredVariable('springLight', '春日光线', '例如：多云天气下明亮均匀的柔光'),
      createRequiredVariable('wardrobe', '服装', '例如：淡鹅黄色针织上衣与白色长裙'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-75',
    title: '秋日旷野电影写真',
    summary: '运用大地色、风和远景尺度呈现具有故事感的秋日肖像。',
    content: '在{{autumnLandscape}}为{{person}}拍摄秋日旷野电影写真，人物呈现{{actionAndMood}}。采用宽幅环境人像构图，让人物占据适中比例，并通过草地、远山和天空形成开阔层次；使用{{goldenLight}}勾勒头发与{{wardrobe}}边缘，保留风吹动植物和衣摆的真实方向，整体以大地色低饱和调色。画面孤独但不消沉，不制造过量落叶或橙色滤镜，不出现倾斜地平线、畸形肢体、重复人物或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['cinematic', 'natural', 'retro'],
    variables: [
      createRequiredVariable('autumnLandscape', '秋日场景', '例如：枯金色草坡与远处低矮山脉'),
      createRequiredVariable('person', '人物设定', '例如：留短发的独立音乐人'),
      createRequiredVariable('actionAndMood', '动作与情绪', '例如：迎风站立并望向远处，神情坚定'),
      createRequiredVariable('goldenLight', '光线', '例如：日落前穿过薄云的侧逆光'),
      createRequiredVariable('wardrobe', '服装', '例如：深棕长风衣与灰色围巾'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-76',
    title: '冬日雪景纯净写真',
    summary: '在雪地高反差环境中保持肤色、层次和安静冬日气息。',
    content: '在{{snowLocation}}为{{person}}拍摄冬日雪景写真，人物正在{{winterAction}}。采用{{framing}}，利用雪地作为自然反光板，在阴天或轻雪中保持面部柔和、服装纹理清晰和背景层次；以{{winterPalette}}控制冷暖平衡，让呼吸雾气和少量飘雪增加真实季节感。画面纯净但不能背景全白，不添加暴雪特效或蓝色滤镜，不出现不合季节服装、冻伤肤色、畸形手部、重复脚印或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['minimal', 'natural', 'cinematic'],
    variables: [
      createRequiredVariable('snowLocation', '雪景地点', '例如：被新雪覆盖的湖边木屋外'),
      createRequiredVariable('person', '人物设定', '例如：戴深红针织帽的长发女生'),
      createRequiredVariable('winterAction', '冬日动作', '例如：双手捧着热饮缓慢走过积雪小径'),
      createRequiredVariable('framing', '景别', '例如：包含环境的四分之三身构图'),
      createRequiredVariable('winterPalette', '冬日配色', '例如：雪白、冷灰、深棕与一点暗红'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-77',
    title: '中式园林雅致写真',
    summary: '借助园林框景、含蓄姿态和东方色彩表现雅致人物。',
    content: '在{{gardenArchitecture}}为{{person}}拍摄中式园林雅致写真，人物穿着{{wardrobe}}并呈现{{gesture}}。利用月洞门、窗棂或廊柱进行自然框景，以中长焦压缩前后院落层次，构图留白含蓄；使用{{lightAndWeather}}表现白墙、青瓦、植物与织物的细微质地，色彩克制并保留真实肤色。画面应尊重建筑和服饰结构，不混杂不同朝代符号，不摆出僵硬戏曲姿势，不出现乱码匾额、畸形手部或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['oriental', 'natural', 'editorial'],
    variables: [
      createRequiredVariable('gardenArchitecture', '园林场景', '例如：雨后有竹影的白墙回廊'),
      createRequiredVariable('person', '人物设定', '例如：气质安静的东方女性'),
      createRequiredVariable('wardrobe', '服装', '例如：剪裁现代的月白色新中式长衫'),
      createRequiredVariable('gesture', '姿态', '例如：在廊下缓步并轻扶一把竹骨伞'),
      createRequiredVariable('lightAndWeather', '光线与天气', '例如：细雨刚停后的柔和天光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-78',
    title: '新中式极简棚拍写真',
    summary: '以现代棚拍结构重新表达东方服装、器物和留白美学。',
    content: '为{{person}}拍摄新中式极简棚拍写真，造型主题为{{stylingConcept}}。人物穿着{{wardrobe}}，与{{prop}}形成简洁的高低和虚实关系；使用85mm人像视角、{{composition}}和单一方向柔光，在中性背景上保留织物纹理、面部轮廓与大面积留白，色彩取自东方传统但降低饱和度。画面现代、克制，不堆叠屏风、折扇、瓷器等符号，不生成错误盘扣、僵硬手势、乱码书法或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['oriental', 'editorial', 'minimal'],
    variables: [
      createRequiredVariable('person', '人物设定', '例如：利落短发的东方男模'),
      createRequiredVariable('stylingConcept', '造型主题', '例如：传统层叠结构的现代转译'),
      createRequiredVariable('wardrobe', '服装', '例如：墨黑交领短外套与宽松灰白长裤'),
      createRequiredVariable('prop', '少量道具', '例如：一块低矮深色天然石'),
      createRequiredVariable('composition', '构图', '例如：人物左置、右侧保留大面积暖灰留白'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-79',
    title: '轻法式室内写真',
    summary: '通过旧公寓细节、优雅松弛姿态和柔和自然光塑造法式气质。',
    content: '在{{interior}}为{{person}}拍摄轻法式室内写真，人物穿着{{wardrobe}}并进行{{activity}}。采用50mm视角，以高窗、旧木地板和少量家具建立空间质感，使用{{windowLight}}呈现柔和肤色、服装垂坠和室内明暗层次；人物姿态优雅但像自然停留的瞬间，色彩为奶油色与低饱和中性色。画面精致但不堆砌奢华陈设，不使用厚重磨皮或泛黄滤镜，不出现镜中重复人物、畸形手指、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['editorial', 'luxury', 'natural'],
    variables: [
      createRequiredVariable('interior', '室内空间', '例如：有雕花墙面和高窗的旧公寓客厅'),
      createRequiredVariable('person', '人物设定', '例如：微卷中长发的成熟女性'),
      createRequiredVariable('wardrobe', '服装', '例如：剪裁简洁的黑色吊带长裙与薄针织外套'),
      createRequiredVariable('activity', '人物动作', '例如：靠在窗边整理刚买回来的花束'),
      createRequiredVariable('windowLight', '窗光', '例如：午后被纱帘柔化的侧光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-80',
    title: '极简纯色棚拍写真',
    summary: '用单色背景、精确姿态和干净布光突出人物本身。',
    content: '为{{person}}拍摄极简纯色棚拍写真，人物造型为{{styling}}。使用{{backgroundColor}}无接缝背景、85mm视角和{{framing}}，通过{{pose}}建立清晰轮廓与肢体线条；大面积柔光作为主光，轻微负补光加强面部结构，背景与服装保持明确但和谐的色彩关系。画面简洁、现代并适合编辑应用，不加入道具、场景装饰或夸张阴影，不进行塑料磨皮，不出现肢体截断错误、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['minimal', 'editorial', 'commercial'],
    variables: [
      createRequiredVariable('person', '人物设定', '例如：五官立体、黑色短发的青年女性'),
      createRequiredVariable('styling', '人物造型', '例如：结构感白色无袖上衣与银色耳饰'),
      createRequiredVariable('backgroundColor', '背景颜色', '例如：低饱和钴蓝色'),
      createRequiredVariable('framing', '景别', '例如：四分之三身纵向构图'),
      createRequiredVariable('pose', '人物姿态', '例如：身体微侧、一手自然垂落并直视镜头'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-81',
    title: '运动活力户外写真',
    summary: '凝固真实运动动作，同时保留环境速度感和健康人物状态。',
    content: '在{{sportsLocation}}为{{athlete}}拍摄运动活力写真，人物正在完成{{movement}}。采用{{cameraApproach}}捕捉正确动作阶段，身体重心、关节方向和装备使用符合运动规律；使用{{lighting}}勾勒肌肉与服装轮廓，背景保留适量方向性运动模糊或空间线条，主体眼神与关键动作清晰。画面有力量但不夸大体型，不制造不可能姿势、错误器材、过量汗水、重复肢体、品牌标志、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['commercial', 'realistic', 'natural'],
    variables: [
      createRequiredVariable('sportsLocation', '运动场景', '例如：清晨海岸旁的城市跑道'),
      createRequiredVariable('athlete', '运动人物', '例如：穿深蓝训练服的女性长跑者'),
      createRequiredVariable('movement', '运动动作', '例如：转过弯道后开始加速'),
      createRequiredVariable('cameraApproach', '拍摄方式', '例如：低机位中焦追拍与高速快门'),
      createRequiredVariable('lighting', '光线', '例如：日出侧逆光与柔和天空补光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-82',
    title: '双人关系叙事写真',
    summary: '通过距离、目光和共同动作表现两个人之间的真实关系。',
    content: '在{{sharedLocation}}为{{twoPeople}}拍摄双人关系写真，记录两人{{interaction}}的瞬间。采用35mm或50mm视角，让双方身体、目光与手部动作形成自然联系，并保留环境中能说明共同经历的细节；使用{{lightingAndMood}}，两人面部曝光一致，服装色彩彼此呼应但不过度搭配。情感应来自真实互动而非模板化拥抱，不交换面部特征，不生成额外人物、纠缠肢体、相同表情、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['natural', 'cinematic', 'healing'],
    variables: [
      createRequiredVariable('sharedLocation', '共同场景', '例如：两人经常见面的社区篮球场看台'),
      createRequiredVariable('twoPeople', '双人关系', '例如：多年未见后重聚的两位老朋友'),
      createRequiredVariable('interaction', '互动瞬间', '例如：并肩坐着分享一张旧照片并相视而笑'),
      createRequiredVariable('lightingAndMood', '光线与氛围', '例如：傍晚柔和侧光与平静怀旧感'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-83',
    title: '亲子陪伴生活写真',
    summary: '记录亲子共同活动中的触碰、回应和自然家庭氛围。',
    content: '在{{familySetting}}为{{parentAndChild}}拍摄亲子陪伴写真，记录他们一起{{sharedActivity}}。使用35mm环境视角和接近孩子高度的机位，优先捕捉眼神回应、手部触碰与自然动作，让空间和物件说明家庭生活；采用{{naturalLight}}，保留成人与孩子真实肤色、年龄特征和服装质地。画面温暖但不强迫看镜头或整齐微笑，不成人化修饰孩子，不出现年龄错误、额外手指、重复人物、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['healing', 'natural', 'realistic'],
    variables: [
      createRequiredVariable('familySetting', '家庭场景', '例如：周末午后的阳台小菜园'),
      createRequiredVariable('parentAndChild', '亲子人物', '例如：年轻父亲和五岁女儿'),
      createRequiredVariable('sharedActivity', '共同活动', '例如：给刚发芽的番茄苗换盆'),
      createRequiredVariable('naturalLight', '自然光线', '例如：遮阳帘过滤后的明亮柔光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-84',
    title: '儿童成长纪实写真',
    summary: '从儿童视角记录探索、专注和成长中的真实动作。',
    content: '在{{childFriendlyLocation}}为{{child}}拍摄成长纪实写真，记录孩子{{exploration}}的过程。相机保持接近儿童视线高度，使用{{framingApproach}}连续呈现环境、动作和细节，允许衣物轻微凌乱、表情变化和真实运动模糊；使用{{lightCondition}}，色彩自然，确保面部、手脚比例和互动对象准确。画面关注探索而非成人式摆拍，不要求孩子持续看镜头，不添加童话特效，不出现年龄失真、畸形手指、危险行为、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['healing', 'natural', 'editorial'],
    variables: [
      createRequiredVariable('childFriendlyLocation', '儿童场景', '例如：雨后有水洼的社区自然乐园'),
      createRequiredVariable('child', '儿童设定', '例如：穿黄色雨衣的六岁男孩'),
      createRequiredVariable('exploration', '探索活动', '例如：蹲下观察水洼里倒映的云和树枝'),
      createRequiredVariable('framingApproach', '构图方式', '例如：包含环境的中景配合手部细节特写'),
      createRequiredVariable('lightCondition', '光线', '例如：雨后明亮阴天光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-85',
    title: '银发长者故事写真',
    summary: '尊重年龄纹理，并通过熟悉环境与物件讲述人物经历。',
    content: '在{{meaningfulPlace}}为{{senior}}拍摄银发长者故事写真，人物正在{{meaningfulActivity}}。采用50mm环境肖像视角，在眼平高度记录自然坐姿或站姿，以{{softLight}}保留皱纹、银发、眼神和手部真实细节，同时让{{storyObject}}作为简洁叙事线索进入构图。画面尊重、沉稳且有生命力，不把年龄痕迹过度磨平，也不刻意制造衰弱感，不出现畸形手部、错误年龄、杂乱纪念物、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['realistic', 'editorial', 'natural'],
    variables: [
      createRequiredVariable('meaningfulPlace', '重要场所', '例如：经营了四十年的小型钟表修理铺'),
      createRequiredVariable('senior', '长者人物', '例如：戴圆框眼镜的银发女钟表师'),
      createRequiredVariable('meaningfulActivity', '人物活动', '例如：用放大镜检查一枚旧机械表'),
      createRequiredVariable('softLight', '光线', '例如：铺面玻璃门进入的柔和侧光'),
      createRequiredVariable('storyObject', '叙事物件', '例如：桌边一张年轻时工作照的相框'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-86',
    title: '男士质感编辑写真',
    summary: '通过克制造型、轮廓布光和真实纹理塑造成熟男性肖像。',
    content: '为{{person}}拍摄男士质感编辑写真，人物形象定位为{{characterQuality}}。穿着{{wardrobe}}，采用{{pose}}，使用85mm视角和简洁中性背景；以{{lighting}}塑造面部骨骼、发型和服装材质，保留胡须、皮肤和细微表情，不进行过度锐化或商业化假笑。构图适合杂志人物页，成熟但不刻板，不堆叠腕表、豪车等身份符号，不夸张肌肉，不出现服装错误、畸形手部、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['editorial', 'realistic', 'minimal'],
    variables: [
      createRequiredVariable('person', '人物设定', '例如：四十岁左右的独立建筑师'),
      createRequiredVariable('characterQuality', '人物气质', '例如：沉着、专注并带有轻微距离感'),
      createRequiredVariable('wardrobe', '服装', '例如：深灰高领针织衫与黑色长外套'),
      createRequiredVariable('pose', '姿态', '例如：侧坐并将双手自然交叠在膝前'),
      createRequiredVariable('lighting', '布光', '例如：窄幅侧上方柔光与深灰负补光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-87',
    title: '水下梦幻人像写真',
    summary: '用真实水下物理、漂浮织物和光线折射营造梦境感。',
    content: '在清澈水下为{{person}}拍摄梦幻人像写真，视觉主题是{{dreamTheme}}。人物穿着{{flowingWardrobe}}并呈现{{underwaterPose}}，头发和织物遵循水流自然展开，身体姿态舒展且关节结构准确；使用从水面投下的{{underwaterLight}}形成柔和光纹、微小气泡和蓝绿色层次，肤色仍保持生命感。画面梦幻但符合浮力与光学规律，不让人物呈溺水痛苦状态，不生成额外肢体、纠缠布料、巨量气泡、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['surreal', 'cinematic', 'fantasy'],
    variables: [
      createRequiredVariable('person', '人物设定', '例如：长发自由漂浮的女性舞者'),
      createRequiredVariable('dreamTheme', '梦境主题', '例如：沉入安静的蓝色记忆'),
      createRequiredVariable('flowingWardrobe', '水下服装', '例如：层次轻薄的灰蓝色长裙'),
      createRequiredVariable('underwaterPose', '水下姿态', '例如：身体微微蜷曲后向上伸展一只手'),
      createRequiredVariable('underwaterLight', '水下光线', '例如：正午水面折射的柔亮波纹光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-88',
    title: '舞者动态艺术写真',
    summary: '精确凝固舞蹈动作，并用布光与空间突出身体线条。',
    content: '在{{danceSpace}}为{{dancer}}拍摄舞者动态艺术写真，凝固{{danceMovement}}的关键瞬间。采用{{cameraAndShutter}}，确保重心、关节、手脚方向和服装运动轨迹符合真实舞蹈逻辑；使用{{stageLighting}}从背景中分离身体轮廓，并保留少量动作余韵与地面接触阴影。画面有力量、节奏和呼吸感，但不把肢体拉伸变形，不制造不可能腾空，不出现额外手脚、错误镜像、观众杂影、文字或水印。',
    categoryId: 'portrait-photography',
    medium: 'photography',
    styleIds: ['cinematic', 'editorial', 'realistic'],
    variables: [
      createRequiredVariable('danceSpace', '舞蹈空间', '例如：有高窗和磨旧木地板的排练厅'),
      createRequiredVariable('dancer', '舞者设定', '例如：穿深色练功服的当代舞者'),
      createRequiredVariable('danceMovement', '舞蹈动作', '例如：旋转结束后单脚落地并向侧上方伸展'),
      createRequiredVariable('cameraAndShutter', '镜头与快门', '例如：低机位50mm视角与高速快门'),
      createRequiredVariable('stageLighting', '舞台光线', '例如：高窗冷光配合一束暖色侧后光'),
    ],
  }),
]

export const PORTRAIT_TEMPLATES = PORTRAIT_PHOTOGRAPHY_TEMPLATES
