import type { PromptTemplate } from '@/types'
import {
  createBuiltinPromptTemplate,
  createRequiredVariable,
} from './createPromptTemplate'

export const PRODUCTS_BRANDS_TEMPLATES: PromptTemplate[] = [
  createBuiltinPromptTemplate({
    id: 'tpl-3',
    title: '极简产品主视觉',
    summary: '适合新品发布和品牌广告的干净产品主视觉。',
    content: '为{{product}}创作一张极简商业产品主视觉，突出{{sellingPoint}}。产品完整、比例准确，置于{{surface}}之上，使用{{backgroundColor}}的纯净渐变背景和克制的几何空间关系；采用略低于产品的三分之四视角，边缘清晰，材质反射符合真实物理。柔和大面积主光配合窄幅轮廓光，保留可控阴影和适量留白，整体高级、简洁、可用于品牌发布，不出现错误文字、重复产品、水印或杂乱道具。',
    categoryId: 'products-brands',
    medium: 'photography',
    styleIds: ['commercial', 'minimal', 'realistic'],
    variables: [
      createRequiredVariable('product', '产品', '例如：磨砂玻璃香水瓶', '磨砂玻璃香水瓶'),
      createRequiredVariable('sellingPoint', '核心卖点', '例如：透明瓶身与金属瓶盖', '透明瓶身与金属瓶盖'),
      createRequiredVariable('surface', '承托表面', '例如：浅灰石材台面', '浅灰石材台面'),
      createRequiredVariable('backgroundColor', '背景色', '例如：暖米白', '暖米白'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-11',
    title: '电商白底商品图',
    summary: '结构准确、背景纯净并适合商品详情页的标准主图。',
    content: '拍摄{{product}}的标准电商白底商品图，准确呈现{{keyDetails}}。产品位于画面中心，保持完整轮廓和真实比例，采用{{viewAngle}}，所有可见部件结构正确；背景为无接缝纯白，使用均匀柔和的棚拍光消除脏污色偏，同时保留必要的接触阴影和材质层次。画面清晰、颜色忠实、边缘干净，不添加场景道具、促销文字、装饰边框、重复商品、水印或夸张反射。',
    categoryId: 'products-brands',
    medium: 'photography',
    styleIds: ['commercial', 'minimal', 'realistic'],
    variables: [
      createRequiredVariable('product', '商品', '例如：白色无线耳机充电盒', '白色无线耳机充电盒'),
      createRequiredVariable('keyDetails', '关键细节', '例如：开盖结构、耳机仓与指示灯', '开盖结构、耳机仓与指示灯'),
      createRequiredVariable('viewAngle', '展示角度', '例如：正面略高三分之四视角', '正面略高三分之四视角'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-12',
    title: '高端美妆材质广告',
    summary: '通过精细材质和克制布光塑造高端美妆品牌气质。',
    content: '为{{cosmetic}}创作高端美妆广告画面，视觉主题是{{concept}}。产品与{{materialElement}}形成简洁的前后层次，包装比例、瓶盖连接和标签区域保持准确，但标签不生成具体文字；采用近距离三分之四视角，突出玻璃、金属或液体的真实材质。使用{{lighting}}制造柔和渐变、高光边缘和干净阴影，整体配色克制奢华，保留大面积品牌留白，不出现多余瓶体、溢出液体、乱码或水印。',
    categoryId: 'products-brands',
    medium: 'photography',
    styleIds: ['luxury', 'commercial', 'minimal'],
    variables: [
      createRequiredVariable('cosmetic', '美妆产品', '例如：琥珀色精华液瓶', '琥珀色精华液瓶'),
      createRequiredVariable('concept', '视觉主题', '例如：夜间修护与水分屏障', '夜间修护与水分屏障'),
      createRequiredVariable('materialElement', '搭配材质', '例如：半透明冰晶与深色石材', '半透明冰晶与深色石材'),
      createRequiredVariable('lighting', '布光', '例如：冷色顶部柔光与暖色轮廓光', '冷色顶部柔光与暖色轮廓光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-30',
    title: '产品爆炸结构图',
    summary: '清晰展示产品部件层级、装配关系和核心技术。',
    content: '为{{product}}制作精确的3D爆炸结构展示图，重点解释{{technicalFeature}}。将外壳、核心组件、连接件和功能模块沿{{explosionDirection}}有序分离，各部件保持统一透视、正确比例和明确装配轴线；使用中性背景、柔和棚拍光与{{materialTreatment}}区分不同材质，接触边缘和内部结构清晰可辨。画面兼具工程可信度与商业完成度，不出现悬浮无关零件、错误连接、尺寸标注、乱码、品牌标志或水印。',
    categoryId: 'products-brands',
    medium: 'three-dimensional',
    styleIds: ['realistic', 'commercial', 'minimal'],
    variables: [
      createRequiredVariable('product', '产品', '例如：便携式降噪耳机'),
      createRequiredVariable('technicalFeature', '核心技术', '例如：折叠转轴与双层声学腔体'),
      createRequiredVariable('explosionDirection', '拆解方向', '例如：沿水平轴由内向外展开'),
      createRequiredVariable('materialTreatment', '材质表现', '例如：深灰金属、哑光塑料与透明剖面'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-31',
    title: '品牌包装插画系统',
    summary: '为系列包装建立可延展的插画母题和识别规则。',
    content: '为{{brandCategory}}设计一套品牌包装插画系统，品牌性格是{{brandPersonality}}。以{{visualMotif}}为核心母题，建立主图形、辅助纹样和边框元素三层结构，让不同包装可以变化构图但保持统一识别；采用{{illustrationTechnique}}和{{palette}}，控制细节密度并为品名、规格和法规信息预留清晰区域。展示三种尺寸的包装应用，图形完整、色彩一致，不生成具体商标、乱码、过度装饰或与品类无关的元素。',
    categoryId: 'products-brands',
    medium: 'illustration',
    styleIds: ['commercial', 'minimal', 'natural'],
    variables: [
      createRequiredVariable('brandCategory', '品牌品类', '例如：植物香氛护理系列'),
      createRequiredVariable('brandPersonality', '品牌性格', '例如：温和、诚实且具有手作感'),
      createRequiredVariable('visualMotif', '视觉母题', '例如：夜间开放的草本植物'),
      createRequiredVariable('illustrationTechnique', '插画技法', '例如：单色木刻线条结合平涂色块'),
      createRequiredVariable('palette', '品牌配色', '例如：松针绿、陶土红与米白'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-32',
    title: '新品发布排版海报',
    summary: '以产品轮廓、卖点层级和品牌留白构成发布物料。',
    content: '为{{product}}设计新品发布排版海报，传播主题为{{launchTheme}}。以产品剪影或局部材质作为主图，使用{{layoutSystem}}组织发布日期占位、产品名称占位和三条卖点信息，字号层级明确，阅读路径从主题到产品再到细节；采用{{palette}}与精细网格，保留高端品牌所需的大面积留白。文字区域使用规则占位而非乱码，不扭曲产品结构，不添加促销贴纸、无关图标、现成商标或水印。',
    categoryId: 'products-brands',
    medium: 'graphic-design',
    styleIds: ['typographic', 'luxury', 'commercial'],
    variables: [
      createRequiredVariable('product', '新品', '例如：钛金属智能腕表'),
      createRequiredVariable('launchTheme', '发布主题', '例如：把时间还给专注'),
      createRequiredVariable('layoutSystem', '版式系统', '例如：十二栏网格与右侧纵向标题'),
      createRequiredVariable('palette', '配色', '例如：曜石黑、钛灰与电光蓝'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-33',
    title: '收藏玩具展示渲染',
    summary: '突出收藏玩具造型、材质和包装陈列感的三维画面。',
    content: '为{{collectible}}创作精致的3D收藏玩具展示渲染，设计主题是{{theme}}。玩具以三分之四视角站立在{{displayBase}}上，身体比例、关节连接和随附配件清楚完整，旁侧放置一件不遮挡主体的包装盒作为尺度参照；使用{{materialStyle}}、柔和顶部主光和窄幅轮廓光，呈现可量产的真实质感。背景简洁，画面具有陈列摄影完成度，不出现重复玩具、悬浮配件、错误文字、现成IP标志或水印。',
    categoryId: 'products-brands',
    medium: 'three-dimensional',
    styleIds: ['miniature', 'commercial', 'healing'],
    variables: [
      createRequiredVariable('collectible', '收藏玩具', '例如：背着种子舱的月球园丁'),
      createRequiredVariable('theme', '设计主题', '例如：在荒芜环境中照料生命'),
      createRequiredVariable('displayBase', '展示底座', '例如：带细小环形山的圆形底座'),
      createRequiredVariable('materialStyle', '材质', '例如：哑光软胶、透明头罩与少量金属'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-34',
    title: '编辑式产品静物',
    summary: '以杂志化构图呈现产品材质、生活方式和品牌气质。',
    content: '为{{product}}拍摄编辑式产品静物，围绕{{lifestyleConcept}}建立画面叙事。将产品与{{supportingObjects}}组织成高低错落但边界清晰的静物构图，使用近距离标准视角和轻微俯拍，重点表现包装、表面纹理与使用痕迹；以{{lighting}}制造克制明暗关系，色彩统一且保留杂志跨页裁切空间。所有道具必须服务于主题，不遮挡产品，不出现重复物件、错误标签、过度反射、乱码或水印。',
    categoryId: 'products-brands',
    medium: 'photography',
    styleIds: ['luxury', 'editorial', 'realistic'],
    variables: [
      createRequiredVariable('product', '产品', '例如：皮革封面的旅行笔记本'),
      createRequiredVariable('lifestyleConcept', '生活方式主题', '例如：缓慢而有意识的远行'),
      createRequiredVariable('supportingObjects', '搭配道具', '例如：黄铜铅笔、折叠地图与一枚石子'),
      createRequiredVariable('lighting', '光线', '例如：百叶窗投下的柔和侧光'),
    ],
  }),
]
