import type { PromptTemplate } from '@/types'
import {
  createBuiltinPromptTemplate,
  createRequiredVariable,
} from './createPromptTemplate'

export const SPACES_ARCHITECTURE_TEMPLATES: PromptTemplate[] = [
  createBuiltinPromptTemplate({
    id: 'tpl-6',
    title: '等距微缩空间',
    summary: '将真实空间转化为清晰可读的等距微缩三维模型。',
    content: '将{{space}}设计为等距视角的微缩3D场景，核心活动是{{activity}}。以切开的盒状空间展示完整布局，家具、人物和道具比例统一，动线清楚，局部加入{{signatureDetail}}作为视觉记忆点。使用圆润但不过度玩具化的建模、细腻粘土与哑光材质，柔和环境光配合顶部主光，阴影短而清晰；背景保持纯净，色彩采用{{palette}}，画面精致、有秩序，不出现悬浮物体、错误透视、乱码或水印。',
    categoryId: 'spaces-architecture',
    medium: 'three-dimensional',
    styleIds: ['miniature', 'healing', 'minimal'],
    variables: [
      createRequiredVariable('space', '空间类型', '例如：深夜营业的小书店', '深夜营业的小书店'),
      createRequiredVariable('activity', '核心活动', '例如：店员整理新到书籍', '店员整理新到书籍'),
      createRequiredVariable('signatureDetail', '标志细节', '例如：通向夹层的红色旋梯', '通向夹层的红色旋梯'),
      createRequiredVariable('palette', '配色', '例如：木色、墨绿与暖黄', '木色、墨绿与暖黄'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-15',
    title: '室内设计效果图',
    summary: '强调空间布局、材料关系和自然采光的写实室内视觉。',
    content: '为{{roomType}}创作写实室内设计效果图，设计方向为{{designStyle}}。从入口附近以约24mm广角观察空间，垂直线保持端正，完整展示主要功能区、家具尺度和通行关系；重点使用{{materials}}，不同表面具有准确的粗糙度、反射和接缝细节。{{lighting}}均匀进入空间，人工辅助光不过曝，明暗层次自然；画面整洁但保留生活感，不出现结构穿插、悬浮家具、重复物件、畸变边缘、文字或水印。',
    categoryId: 'spaces-architecture',
    medium: 'three-dimensional',
    styleIds: ['realistic', 'minimal', 'natural'],
    variables: [
      createRequiredVariable('roomType', '空间类型', '例如：开放式客餐厅', '开放式客餐厅'),
      createRequiredVariable('designStyle', '设计方向', '例如：温暖现代主义', '温暖现代主义'),
      createRequiredVariable('materials', '主要材料', '例如：浅橡木、洞石与米色织物', '浅橡木、洞石与米色织物'),
      createRequiredVariable('lighting', '采光条件', '例如：午后从落地窗进入的自然光', '午后从落地窗进入的自然光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-16',
    title: '建筑外观叙事摄影',
    summary: '同时表达建筑形体、环境关系和使用者尺度的外观图。',
    content: '拍摄位于{{environment}}中的{{building}}，突出{{architecturalFeature}}。使用24mm移轴建筑摄影视角，保持垂直线准确，从{{viewpoint}}展示完整体量、入口关系和周边景观；加入少量自然活动的人物作为尺度参照，但不遮挡建筑。选择{{weatherAndLight}}塑造立面层次，玻璃、混凝土、木材等材质反射真实，天空与地面不过度处理，不出现倾斜结构、重复窗格、夸张HDR、文字或水印。',
    categoryId: 'spaces-architecture',
    medium: 'photography',
    styleIds: ['realistic', 'editorial'],
    variables: [
      createRequiredVariable('environment', '周边环境', '例如：滨水公共公园', '滨水公共公园'),
      createRequiredVariable('building', '建筑类型', '例如：当代木结构图书馆', '当代木结构图书馆'),
      createRequiredVariable('architecturalFeature', '建筑特点', '例如：层叠挑檐与通透首层', '层叠挑檐与通透首层'),
      createRequiredVariable('viewpoint', '观察位置', '例如：入口广场的斜侧方', '入口广场的斜侧方'),
      createRequiredVariable('weatherAndLight', '天气与光线', '例如：薄云天气下的傍晚柔光', '薄云天气下的傍晚柔光'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-40',
    title: '建筑剖面轴测图',
    summary: '在一张图中说明建筑空间、结构和人物活动关系。',
    content: '为{{buildingType}}绘制建筑剖面轴测图，重点说明{{designIdea}}。以统一的平行投影切开建筑，清楚展示楼层、楼梯、结构框架、主要家具与室内外连接，加入少量比例准确的人物表现{{activities}}；使用{{lineAndColorStyle}}区分承重结构、围护界面和活动区域，并保留足够注释留白。图面精确、层级清楚，不混用透视，不生成不可能结构、装饰性尺寸、乱码或水印。',
    categoryId: 'spaces-architecture',
    medium: 'illustration',
    styleIds: ['editorial', 'minimal', 'realistic'],
    variables: [
      createRequiredVariable('buildingType', '建筑类型', '例如：社区共享图书馆'),
      createRequiredVariable('designIdea', '设计理念', '例如：围绕中央采光庭院组织公共活动'),
      createRequiredVariable('activities', '人物活动', '例如：阅读、讨论与儿童工作坊'),
      createRequiredVariable('lineAndColorStyle', '线条与配色', '例如：精细黑线、浅灰结构与橙色活动节点'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-41',
    title: '公共空间导视系统',
    summary: '展示标识层级、方向编码和实际空间应用。',
    content: '为{{publicSpace}}设计一套公共导视系统，核心需求是{{wayfindingGoal}}。建立入口总览、方向指引、楼层编号和房间标识四个层级，使用{{visualSystem}}统一箭头、图标、颜色编码与中英文字占位；在{{applicationScenes}}中展示真实比例和安装方式，确保远距离可读、无障碍且不遮挡建筑动线。版式简洁，不生成具体乱码，不使用过多颜色、相互冲突的箭头、难辨认图标、品牌商标或水印。',
    categoryId: 'spaces-architecture',
    medium: 'graphic-design',
    styleIds: ['typographic', 'minimal', 'commercial'],
    variables: [
      createRequiredVariable('publicSpace', '公共空间', '例如：多层当代艺术中心'),
      createRequiredVariable('wayfindingGoal', '导视目标', '例如：帮助首次到访者快速找到展厅与服务设施'),
      createRequiredVariable('visualSystem', '视觉系统', '例如：超粗无衬线字体、模块化箭头与楼层色带'),
      createRequiredVariable('applicationScenes', '应用场景', '例如：入口立柱、墙面转角与电梯厅'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-42',
    title: '概念展亭可视化',
    summary: '用三维场景表达临时展亭的结构概念和参观体验。',
    content: '为{{exhibitionTheme}}设计一座概念展亭并制作3D可视化，空间概念为{{spatialConcept}}。展亭位于{{site}}，采用{{materials}}形成清晰结构逻辑和入口序列，人物尺度准确，参观路径从外部聚集区自然进入核心展陈空间；使用广角但不过度变形的视角、真实环境光和适量体积效果。造型可以实验但必须可建造，不出现悬空受力、封闭入口、重复人物、文字标牌或水印。',
    categoryId: 'spaces-architecture',
    medium: 'three-dimensional',
    styleIds: ['surreal', 'minimal', 'realistic'],
    variables: [
      createRequiredVariable('exhibitionTheme', '展览主题', '例如：城市中的声音记忆'),
      createRequiredVariable('spatialConcept', '空间概念', '例如：层层展开的声波环'),
      createRequiredVariable('site', '场地', '例如：河岸公园的开阔草地'),
      createRequiredVariable('materials', '主要材料', '例如：半透明再生板材与轻型木结构'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-43',
    title: '夜景街区人文摄影',
    summary: '捕捉建筑灯光、街道活动和真实城市生活的关系。',
    content: '在{{district}}拍摄夜景街区人文照片，重点记录{{urbanActivity}}。使用35mm视角和行人高度，将发光店面、建筑立面、道路反射与人物活动组织成具有纵深的构图；以{{weather}}增强空气和地面质感，保留混合色温与暗部细节，人物动作自然且不过度凝固。画面具有电影感但仍像真实城市观察，不制造空城或过量霓虹，不出现重复行人、畸形车辆、乱码招牌或水印。',
    categoryId: 'spaces-architecture',
    medium: 'photography',
    styleIds: ['cinematic', 'realistic', 'natural'],
    variables: [
      createRequiredVariable('district', '街区', '例如：高架桥下逐渐复兴的老商业街'),
      createRequiredVariable('urbanActivity', '城市活动', '例如：夜班结束的人们在小店吃宵夜'),
      createRequiredVariable('weather', '天气', '例如：小雨刚停、路面仍然湿润'),
    ],
  }),
  createBuiltinPromptTemplate({
    id: 'tpl-44',
    title: '历史建筑水彩记录',
    summary: '以手绘方式记录历史建筑比例、材料和环境气息。',
    content: '绘制{{historicBuilding}}的建筑水彩记录，观察重点是{{architecturalFeature}}。采用{{viewpoint}}准确呈现整体比例、屋顶轮廓、门窗节奏和材料老化痕迹，周围加入少量{{contextElements}}说明建筑与街道的关系；使用轻盈铅笔底稿、透明水彩叠色和自然留白，光线为{{lighting}}。画面保留现场速写的呼吸感但结构可信，不任意改造立面，不加入现代广告、夸张透视、可读文字或水印。',
    categoryId: 'spaces-architecture',
    medium: 'illustration',
    styleIds: ['oriental', 'natural', 'retro'],
    variables: [
      createRequiredVariable('historicBuilding', '历史建筑', '例如：江南水岸的百年木构会馆'),
      createRequiredVariable('architecturalFeature', '建筑特征', '例如：层叠屋檐与临水柱廊'),
      createRequiredVariable('viewpoint', '观察视角', '例如：河对岸的斜侧全景'),
      createRequiredVariable('contextElements', '环境元素', '例如：石桥、旧树与经过的居民'),
      createRequiredVariable('lighting', '光线', '例如：阴天柔光与潮湿空气'),
    ],
  }),
]
