import { createPromptChoices } from './helpers'
import type { PromptTaxonomyDomainDefinition } from './types'

const STANDARD_CAMERA_HEIGHT_IDS = [
  'module-angle-ground-level',
  'module-angle-waist-level',
  'module-angle-low',
  'module-angle-eye',
  'module-angle-high',
]

const LOCAL_BODY_PART_IDS = ['module-subject-hands', 'module-subject-feet-only']

export default {
  id: 'domain-camera',
  label: '相机与画面',
  description: '拍摄平台确定后，景别、机位高度、仰俯角、方位、焦段和焦点继续作为独立控制轴。',
  sortOrder: 50,
  groups: [
    {
      id: 'group-camera-framing',
      label: '景别',
      description: '选择主体在画面中的主要取景范围。',
      outputLabel: '景别',
      sortOrder: 10,
      selectionMode: 'single',
      maxSelections: 1,
      choices: [
        ...createPromptChoices([
          'module-shot-extreme-closeup',
          'module-shot-detail',
        ]),
        ...createPromptChoices([
          'module-shot-closeup',
          'module-shot-near',
          'module-shot-bust',
          'module-shot-three-quarter',
          'module-shot-medium',
          'module-shot-calf',
          'module-shot-full',
          'module-shot-wide',
        ], 30).map(choice => ({
          ...choice,
          enabledWhen: { noneOf: LOCAL_BODY_PART_IDS },
        })),
      ],
    },
    {
      id: 'group-camera-subject-occupancy',
      label: '主体占幅',
      description: '在既定景别基础上，控制完整主体在画面中占据得更紧或更松。',
      outputLabel: '主体占幅',
      sortOrder: 20,
      selectionMode: 'single',
      maxSelections: 1,
      visibleWhen: { noneOf: LOCAL_BODY_PART_IDS },
      choices: createPromptChoices([
        'module-shot-tight-full',
        'module-shot-loose-full',
      ]),
    },
    {
      id: 'group-camera-crop',
      label: '完整性与裁切',
      description: '指定群体、局部或横纵延展主体需要保留的边界。',
      outputLabel: '画面裁切',
      sortOrder: 30,
      selectionMode: 'single',
      maxSelections: 1,
      visibleWhen: { noneOf: LOCAL_BODY_PART_IDS },
      choices: [
        {
          id: 'module-shot-group-full',
          sortOrder: 10,
          enabledWhen: {
            anyOf: [
              'module-subject-pair',
              'module-subject-group',
              'module-subject-crowd',
            ],
          },
        },
        ...createPromptChoices([
          'module-shot-upper-section',
          'module-shot-middle-section',
          'module-shot-lower-section',
          'module-shot-horizontal-full',
          'module-shot-vertical-full',
        ], 20),
      ],
    },
    {
      id: 'group-camera-height',
      label: '相机高度',
      description: '只定义镜头中心相对主体的高低，不自动决定光轴向上还是向下。',
      outputLabel: '相机高度',
      sortOrder: 40,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices(STANDARD_CAMERA_HEIGHT_IDS),
    },
    {
      id: 'group-camera-pitch',
      label: '仰俯角度',
      description: '相机高度和光轴角度分开选择；低位并不自动等于仰拍。',
      outputLabel: '相机角度',
      sortOrder: 50,
      selectionMode: 'single',
      maxSelections: 1,
      choices: [
        ...createPromptChoices([
          'module-angle-level-pitch',
          'module-angle-upward-pitch',
          'module-angle-downward-pitch',
        ]),
        {
          id: 'module-angle-overhead',
          sortOrder: 40,
          excludes: STANDARD_CAMERA_HEIGHT_IDS,
        },
        {
          id: 'module-angle-nadir',
          sortOrder: 50,
          excludes: STANDARD_CAMERA_HEIGHT_IDS,
        },
      ],
    },
    {
      id: 'group-camera-azimuth',
      label: '绕主体方位',
      description: '定义摄影机从主体正前、侧面或后方哪个方向观察。',
      outputLabel: '观察方位',
      sortOrder: 60,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-angle-front',
        'module-angle-front-three-quarter',
        'module-angle-profile',
        'module-angle-rear-three-quarter',
        'module-angle-rear',
      ]),
    },
    {
      id: 'group-camera-roll',
      label: '画面旋转',
      description: '仅控制机身绕光轴旋转，不改变机位高低和观察方位。',
      outputLabel: '画面旋转',
      sortOrder: 70,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices(['module-angle-dutch']),
    },
    {
      id: 'group-camera-narrative-view',
      label: '叙事视角',
      description: '需要明确观察者关系时，再选择过肩或主观视角。',
      outputLabel: '叙事视角',
      sortOrder: 80,
      selectionMode: 'single',
      maxSelections: 1,
      choices: [
        {
          id: 'module-angle-shoulder',
          sortOrder: 10,
          enabledWhen: {
            anyOf: [
              'module-subject-pair',
              'module-subject-group',
              'module-subject-crowd',
            ],
          },
        },
        {
          id: 'module-angle-pov',
          sortOrder: 20,
        },
      ],
    },
    {
      id: 'group-camera-special-view',
      label: '专项观察方式',
      description: '用于产品、建筑或几何主体的端向、切线和轴测观察。',
      outputLabel: '专项视角',
      sortOrder: 90,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-angle-end-on',
        'module-angle-tangential',
        'module-angle-isometric',
      ]),
    },
    {
      id: 'group-camera-focal-length',
      label: '焦段',
      description: '焦段与光学投影、景深和微距能力分别选择。',
      outputLabel: '镜头焦段',
      sortOrder: 100,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-lens-14mm-rectilinear',
        'module-lens-24mm',
        'module-lens-28mm',
        'module-lens-35mm',
        'module-lens-40mm',
        'module-lens-50mm',
        'module-lens-65mm',
        'module-lens-85mm',
        'module-lens-macro-100mm',
        'module-lens-telephoto',
      ]),
    },
    {
      id: 'group-camera-optics',
      label: '特殊光学',
      description: '未选择时使用常规直线投影；这里只添加特殊镜头行为。',
      outputLabel: '特殊光学',
      sortOrder: 110,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-lens-fisheye',
        'module-lens-shift',
        'module-lens-telecentric',
        'module-lens-anamorphic',
      ]),
    },
    {
      id: 'group-camera-focus',
      label: '焦点与景深',
      description: '焦点策略与焦段独立，可以在同一焦段下选择浅景深、深焦或特殊焦平面。',
      outputLabel: '焦点与景深',
      sortOrder: 120,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-lens-ultra-shallow',
        'module-lens-deep-focus',
        'module-lens-tilt',
        'module-lens-split-diopter',
      ]),
    },
    {
      id: 'group-camera-magnification',
      label: '放大能力',
      description: '微距能力不再与 100mm 焦段绑定。',
      outputLabel: '放大方式',
      sortOrder: 130,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices(['module-lens-macro-capability']),
    },
  ],
} satisfies PromptTaxonomyDomainDefinition
