import { createPromptChoices } from './helpers'
import type { PromptTaxonomyDomainDefinition } from './types'

const COLOR_DEPENDENT_IDS = [
  'module-color-natural',
  'module-color-warm',
  'module-color-cool',
  'module-color-monochrome',
  'module-color-primary-triad',
  'module-color-split-complementary',
  'module-color-cyan-analogous',
  'module-color-purple-yellow',
  'module-color-red-cyan',
  'module-color-neutral-accent',
  'module-color-pastel',
  'module-color-earth',
  'module-color-jewel',
  'module-color-low-saturation',
  'module-color-medium-saturation',
  'module-color-vivid',
]

export default {
  id: 'domain-color',
  label: '色彩与调色',
  description: '黑白模式、白平衡、色相关系、饱和度和明度分别控制。',
  sortOrder: 80,
  groups: [
    {
      id: 'group-color-mode',
      label: '黑白模式',
      description: '选择黑白后会清除不再有效的彩色色相与饱和度选择。',
      outputLabel: '色彩模式',
      sortOrder: 10,
      selectionMode: 'single',
      maxSelections: 1,
      choices: [
        {
          id: 'module-color-grayscale',
          sortOrder: 10,
          excludes: COLOR_DEPENDENT_IDS,
        },
      ],
    },
    {
      id: 'group-color-white-balance',
      label: '白平衡倾向',
      description: '只控制整体冷暖偏移，不同时限定饱和度。',
      outputLabel: '白平衡',
      sortOrder: 20,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-color-natural',
        'module-color-warm',
        'module-color-cool',
      ]),
    },
    {
      id: 'group-color-hue-relationship',
      label: '色相关系',
      description: '规定颜色之间采用单色、邻近、互补或三元组织。',
      outputLabel: '色相关系',
      sortOrder: 30,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-color-monochrome',
        'module-color-primary-triad',
        'module-color-split-complementary',
        'module-color-cyan-analogous',
        'module-color-purple-yellow',
        'module-color-red-cyan',
        'module-color-neutral-accent',
      ]),
    },
    {
      id: 'group-color-palette',
      label: '具体色系',
      description: '需要明确颜色家族时，再补充粉彩、大地色或宝石深彩。',
      outputLabel: '具体色系',
      sortOrder: 40,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-color-pastel',
        'module-color-earth',
        'module-color-jewel',
      ]),
    },
    {
      id: 'group-color-saturation',
      label: '饱和度',
      description: '饱和度与冷暖、明度和色相关系独立。',
      outputLabel: '饱和度',
      sortOrder: 50,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-color-low-saturation',
        'module-color-medium-saturation',
        'module-color-vivid',
      ]),
    },
    {
      id: 'group-color-luminance',
      label: '整体明度',
      description: '选择高调、中间调或低调亮度分布。',
      outputLabel: '整体明度',
      sortOrder: 60,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-color-high-luminance',
        'module-color-medium-luminance',
        'module-color-low-luminance',
      ]),
    },
  ],
} satisfies PromptTaxonomyDomainDefinition
