import { createPromptChoices } from './helpers'
import type { PromptTaxonomyDomainDefinition } from './types'

export default {
  id: 'domain-composition',
  label: '构图与空间',
  description: '主体位置、平衡、视线路径、结构模式和空间层次分组选择，可以合理叠加。',
  sortOrder: 60,
  groups: [
    {
      id: 'group-composition-placement',
      label: '主体位置',
      description: '规定主要视觉中心在画框中的基础位置。',
      outputLabel: '主体位置',
      sortOrder: 10,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-composition-centered',
        'module-composition-thirds',
        'module-composition-golden-ratio',
      ]),
    },
    {
      id: 'group-composition-balance',
      label: '画面平衡',
      description: '控制左右视觉重量和负空间关系，不替代主体位置。',
      outputLabel: '画面平衡',
      sortOrder: 20,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-composition-symmetry',
        'module-composition-asymmetric-balance',
        'module-composition-negative',
      ]),
    },
    {
      id: 'group-composition-path',
      label: '视觉路径',
      description: '选择线条和元素如何引导观看顺序。',
      outputLabel: '视觉路径',
      sortOrder: 30,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-composition-diagonal',
        'module-composition-leading-lines',
        'module-composition-s-curve',
        'module-composition-z-path',
        'module-composition-golden-spiral',
      ]),
    },
    {
      id: 'group-composition-structure',
      label: '结构模式',
      description: '使用几何结构或分区方式组织多个视觉节点。',
      outputLabel: '构图结构',
      sortOrder: 40,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-composition-triangle',
        'module-composition-radial',
        'module-composition-circular',
        'module-composition-grid',
        'module-composition-horizontal-layers',
        'module-composition-vertical-columns',
      ]),
    },
    {
      id: 'group-composition-depth',
      label: '空间层次',
      description: '控制画面是否通过内框或前中后景建立深度。',
      outputLabel: '空间层次',
      sortOrder: 50,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-composition-frame-within-frame',
        'module-composition-depth-layers',
      ]),
    },
    {
      id: 'group-composition-multiple-subjects',
      label: '多元素组织',
      description: '多个主体或重复元素出现时，继续规定其排列方式。',
      outputLabel: '多元素组织',
      sortOrder: 60,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-composition-repetition',
        'module-composition-odd-group',
        'module-composition-scatter',
      ]),
    },
  ],
} satisfies PromptTaxonomyDomainDefinition
