import { createPromptChoices } from './helpers'
import type { PromptTaxonomyDomainDefinition } from './types'

export default {
  id: 'domain-lighting',
  label: '光线与反差',
  description: '光源、方向、软硬、反差和特殊投影分别选择，不再使用整套布光预设。',
  sortOrder: 70,
  groups: [
    {
      id: 'group-lighting-source',
      label: '主要光源',
      description: '选择提供主要照度的光源类别。',
      outputLabel: '主要光源',
      sortOrder: 10,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-lighting-daylight',
        'module-lighting-window',
        'module-lighting-studio',
        'module-lighting-neon',
        'module-lighting-overcast',
        'module-lighting-low-point',
      ]),
    },
    {
      id: 'group-lighting-direction',
      label: '主光方向',
      description: '只定义主光从哪个方向到达主体。',
      outputLabel: '主光方向',
      sortOrder: 20,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-lighting-frontal-soft',
        'module-lighting-top-front',
        'module-lighting-upper-side',
        'module-lighting-split',
        'module-lighting-backlight',
        'module-lighting-overhead-soft',
        'module-lighting-underlight',
      ]),
    },
    {
      id: 'group-lighting-quality',
      label: '光质软硬',
      description: '光质由光源相对尺寸决定，与方向保持独立。',
      outputLabel: '光质',
      sortOrder: 30,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-lighting-soft-quality',
        'module-lighting-medium-quality',
        'module-lighting-hard-quality',
      ]),
    },
    {
      id: 'group-lighting-contrast',
      label: '明暗反差',
      description: '控制受光区与阴影区的亮度差异。',
      outputLabel: '明暗反差',
      sortOrder: 40,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-lighting-low-contrast',
        'module-lighting-medium-contrast',
        'module-lighting-high-contrast',
      ]),
    },
    {
      id: 'group-lighting-natural-state',
      label: '自然光状态',
      description: '在使用自然光时，可继续指定正午、黎明或暮后天光的实际状态。',
      outputLabel: '自然光状态',
      sortOrder: 50,
      selectionMode: 'single',
      maxSelections: 1,
      visibleWhen: {
        anyOf: [
          'module-lighting-daylight',
          'module-lighting-window',
          'module-lighting-overcast',
        ],
      },
      choices: createPromptChoices([
        'module-lighting-noon',
        'module-lighting-dawn',
        'module-lighting-afterglow',
      ]),
    },
    {
      id: 'group-lighting-effects',
      label: '辅助与投影效果',
      description: '按需叠加最多两项局部聚光、条纹投影或轮廓辅助光。',
      outputLabel: '光线效果',
      sortOrder: 60,
      selectionMode: 'multiple',
      maxSelections: 2,
      choices: createPromptChoices([
        'module-lighting-dramatic',
        'module-lighting-blinds',
        'module-lighting-rim',
      ]),
    },
  ],
} satisfies PromptTaxonomyDomainDefinition
