import { createPromptChoices } from './helpers'
import type { PromptTaxonomyDomainDefinition } from './types'

export default {
  id: 'domain-medium',
  label: '媒介与拍摄',
  description: '先决定画面如何形成；只有摄影分支会继续出现固定机位、人手持和无人机控制。',
  sortOrder: 40,
  groups: [
    {
      id: 'group-medium-family',
      label: '表现媒介',
      description: '选择摄影、二维绘画或三维渲染后，再进入该媒介独有的下级控制。',
      outputLabel: '表现媒介',
      sortOrder: 10,
      selectionMode: 'single',
      maxSelections: 1,
      choices: [
        {
          id: 'module-style-photography',
          sortOrder: 10,
          children: [
            {
              id: 'group-medium-photography-language',
              label: '摄影表达',
              description: '在摄影媒介内继续选择画面用途和观察方式。',
              outputLabel: '摄影表达',
              sortOrder: 10,
              selectionMode: 'single',
              maxSelections: 1,
              choices: createPromptChoices([
                'module-style-photorealistic',
                'module-style-documentary',
                'module-style-editorial',
                'module-style-cinematic',
              ]),
            },
            {
              id: 'group-medium-photography-process',
              label: '成像工艺',
              description: '成像工艺与拍摄平台分开选择。未选择时不额外限定胶片或即时相纸。',
              outputLabel: '成像工艺',
              sortOrder: 20,
              selectionMode: 'single',
              maxSelections: 1,
              choices: createPromptChoices([
                'module-style-negative-film',
                'module-style-instant-film',
              ]),
            },
            {
              id: 'group-capture-platform',
              label: '拍摄平台',
              description: '选择固定机位、人手持或无人机后，只显示该平台专属控制。',
              outputLabel: '拍摄方式',
              sortOrder: 30,
              selectionMode: 'single',
              maxSelections: 1,
              choices: [
                {
                  id: 'module-capture-fixed',
                  sortOrder: 10,
                  children: [
                    {
                      id: 'group-capture-fixed-support',
                      label: '固定支撑方式',
                      description: '选择固定机位后，继续指定相机如何被稳定承载。',
                      outputLabel: '固定支撑',
                      sortOrder: 10,
                      selectionMode: 'single',
                      maxSelections: 1,
                      choices: createPromptChoices([
                        'module-capture-tripod',
                        'module-capture-rigid-mount',
                      ]),
                    },
                    {
                      id: 'group-capture-fixed-motion',
                      label: '固定机位运动',
                      description: '基座固定时，可以完全静止，也可以仅绕稳定轴线受控摇摄。',
                      outputLabel: '机位运动',
                      sortOrder: 20,
                      selectionMode: 'single',
                      maxSelections: 1,
                      choices: createPromptChoices([
                        'module-capture-fixed-static',
                        'module-capture-fixed-pan',
                      ]),
                    },
                  ],
                },
                {
                  id: 'module-capture-handheld',
                  sortOrder: 20,
                  children: [
                    {
                      id: 'group-capture-handheld-posture',
                      label: '摄影者持机姿势',
                      description: '这里描述摄影者如何持机，不是被摄人物的身体姿态。',
                      outputLabel: '摄影者姿势',
                      sortOrder: 10,
                      selectionMode: 'single',
                      maxSelections: 1,
                      choices: createPromptChoices([
                        'module-capture-operator-standing',
                        'module-capture-operator-crouching',
                        'module-capture-operator-ground',
                      ]),
                    },
                    {
                      id: 'group-capture-handheld-height',
                      label: '持机高度',
                      description: '指定相机相对摄影者身体的位置；主体相对机位高度在相机几何中继续选择。',
                      outputLabel: '持机高度',
                      sortOrder: 20,
                      selectionMode: 'single',
                      maxSelections: 1,
                      choices: createPromptChoices([
                        'module-capture-height-eye',
                        'module-capture-height-chest',
                        'module-capture-height-waist',
                        'module-capture-height-low',
                        'module-capture-height-raised',
                      ]),
                    },
                    {
                      id: 'group-capture-handheld-stability',
                      label: '手持稳定方式',
                      description: '选择自然手持漂移，或使用稳定器隔离步伐与腕部震动。',
                      outputLabel: '手持稳定',
                      sortOrder: 30,
                      selectionMode: 'single',
                      maxSelections: 1,
                      choices: createPromptChoices([
                        'module-capture-natural-stability',
                        'module-capture-gimbal',
                      ]),
                    },
                    {
                      id: 'group-capture-handheld-motion',
                      label: '手持运动状态',
                      description: '区分摄影者原地观察和随主体移动的手持跟拍。',
                      outputLabel: '手持运动',
                      sortOrder: 40,
                      selectionMode: 'single',
                      maxSelections: 1,
                      choices: createPromptChoices([
                        'module-capture-handheld-observe',
                        'module-capture-handheld-follow',
                      ]),
                    },
                  ],
                },
                {
                  id: 'module-capture-drone',
                  sortOrder: 30,
                  children: [
                    {
                      id: 'group-capture-drone-altitude',
                      label: '无人机高度',
                      description: '先确定飞行高度，再到相机几何中选择斜拍、俯拍或垂直顶视。',
                      outputLabel: '无人机高度',
                      sortOrder: 10,
                      selectionMode: 'single',
                      maxSelections: 1,
                      choices: createPromptChoices([
                        'module-capture-drone-low',
                        'module-capture-drone-medium',
                        'module-capture-drone-high',
                      ]),
                    },
                    {
                      id: 'group-capture-drone-path',
                      label: '无人机飞行路径',
                      description: '飞行路径只描述平台运动，不替代镜头朝向。',
                      outputLabel: '无人机运动',
                      sortOrder: 20,
                      selectionMode: 'single',
                      maxSelections: 1,
                      choices: createPromptChoices([
                        'module-capture-drone-hover',
                        'module-capture-drone-forward',
                        'module-capture-drone-orbit',
                        'module-capture-drone-follow',
                      ]),
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: 'module-style-two-dimensional',
          sortOrder: 20,
          children: [
            {
              id: 'group-medium-two-dimensional-technique',
              label: '二维技法',
              description: '选择具体绘画、印刷或拼贴技法。',
              outputLabel: '二维技法',
              sortOrder: 10,
              selectionMode: 'single',
              maxSelections: 1,
              choices: createPromptChoices([
                'module-style-ink',
                'module-style-oil',
                'module-style-watercolor',
                'module-style-woodblock',
                'module-style-colored-pencil',
                'module-style-paper-collage',
                'module-style-halftone-comic',
                'module-style-flat',
              ]),
            },
          ],
        },
        {
          id: 'module-style-three-dimensional',
          sortOrder: 30,
          children: [
            {
              id: 'group-medium-three-dimensional-rendering',
              label: '三维表现方式',
              description: '选择几何造型和渲染表面的主要表现方式。',
              outputLabel: '三维表现',
              sortOrder: 10,
              selectionMode: 'single',
              maxSelections: 1,
              choices: createPromptChoices([
                'module-style-pbr',
                'module-style-clay',
                'module-style-low-poly',
                'module-style-voxel',
              ]),
            },
          ],
        },
      ],
    },
  ],
} satisfies PromptTaxonomyDomainDefinition
