import { createPromptChoices } from './helpers'
import type { PromptTaxonomyDomainDefinition } from './types'

export default {
  id: 'domain-scene',
  label: '场景与时空',
  description: '先选空间类型，再逐级显示具体地点；时间、天气、尺度和环境密度保持独立。',
  sortOrder: 30,
  groups: [
    {
      id: 'group-scene-space-family',
      label: '空间类型',
      description: '选择空间大类后，只显示属于该分支的具体地点。',
      outputLabel: '空间类型',
      sortOrder: 10,
      selectionMode: 'single',
      maxSelections: 1,
      choices: [
        {
          id: 'module-environment-studio',
          sortOrder: 10,
        },
        {
          id: 'module-environment-indoor-generic',
          sortOrder: 20,
          children: [
            {
              id: 'group-scene-indoor-location',
              label: '室内地点',
              description: '继续细化室内空间的具体用途和结构。',
              outputLabel: '具体地点',
              sortOrder: 10,
              selectionMode: 'single',
              maxSelections: 1,
              choices: createPromptChoices([
                'module-environment-interior',
                'module-environment-workshop',
                'module-environment-greenhouse',
                'module-environment-gallery',
              ]),
            },
          ],
        },
        {
          id: 'module-environment-urban-generic',
          sortOrder: 30,
          children: [
            {
              id: 'group-scene-urban-location',
              label: '城市地点',
              description: '继续选择城市环境中的具体空间。',
              outputLabel: '具体地点',
              sortOrder: 10,
              selectionMode: 'single',
              maxSelections: 1,
              choices: createPromptChoices([
                'module-environment-city',
                'module-environment-alley',
                'module-environment-rooftop',
              ]),
            },
          ],
        },
        {
          id: 'module-environment-natural-generic',
          sortOrder: 40,
          children: [
            {
              id: 'group-scene-natural-location',
              label: '自然地点',
              description: '继续选择明确自然地貌或生态环境。',
              outputLabel: '具体地点',
              sortOrder: 10,
              selectionMode: 'single',
              maxSelections: 1,
              choices: createPromptChoices([
                'module-environment-nature',
                'module-environment-bamboo',
                'module-environment-alpine-lake',
                'module-environment-coastal-cliff',
                'module-environment-dunes',
                'module-environment-snow-forest',
                'module-environment-wetland',
                'module-environment-limestone-cave',
              ]),
            },
          ],
        },
        {
          id: 'module-environment-semi-outdoor',
          sortOrder: 50,
          children: [
            {
              id: 'group-scene-semi-outdoor-location',
              label: '半室外地点',
              description: '继续选择具有围合边界但与室外连通的地点。',
              outputLabel: '具体地点',
              sortOrder: 10,
              selectionMode: 'single',
              maxSelections: 1,
              choices: createPromptChoices(['module-environment-courtyard']),
            },
          ],
        },
      ],
    },
    {
      id: 'group-scene-time',
      label: '时间阶段',
      description: '只规定事件发生时间，不在此处替代具体布光选择。',
      outputLabel: '场景时间',
      sortOrder: 20,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-environment-time-dawn',
        'module-environment-time-day',
        'module-environment-time-noon',
        'module-environment-time-dusk',
        'module-environment-time-blue-hour',
        'module-environment-time-night',
      ]),
    },
    {
      id: 'group-scene-weather',
      label: '天气',
      description: '天气独立于地点和时间，同一地点可在不同天气下使用。',
      outputLabel: '天气',
      sortOrder: 30,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-environment-weather-clear',
        'module-environment-weather-overcast',
        'module-environment-rain',
        'module-environment-weather-snow',
        'module-environment-weather-fog',
      ]),
    },
    {
      id: 'group-scene-ground-state',
      label: '地面状态',
      description: '仅在需要时增加地表条件，不随雨天自动勾选。',
      outputLabel: '地面状态',
      sortOrder: 40,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices(['module-environment-ground-wet']),
    },
    {
      id: 'group-scene-scale',
      label: '空间尺度',
      description: '控制主体与空间边界之间的相对尺度。',
      outputLabel: '空间尺度',
      sortOrder: 50,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-environment-scale-enclosed',
        'module-environment-scale-compact',
        'module-environment-scale-open',
        'module-environment-scale-monumental',
      ]),
    },
    {
      id: 'group-scene-density',
      label: '环境密度',
      description: '控制环境信息量，不改变已选择的地点类别。',
      outputLabel: '环境密度',
      sortOrder: 60,
      selectionMode: 'single',
      maxSelections: 1,
      choices: createPromptChoices([
        'module-environment-density-minimal',
        'module-environment-density-controlled',
        'module-environment-density-natural',
        'module-environment-density-dense',
      ]),
    },
  ],
} satisfies PromptTaxonomyDomainDefinition
